FROM node:20-alpine

# Instalujemy zależności systemowe potrzebne do kompilacji niektórych paczek npm
RUN apk add --no-cache libc6-compat

RUN apk add --no-cache ffmpeg

WORKDIR /app

# Kopiujemy pliki definicji zależności
COPY package*.json ./

# Instalujemy wszystkie zależności (w tym ts-node-dev do hot reloadingu)
RUN npm install

# Kopiujemy całą resztę kodu (src, proto, configi)
COPY . .

# Otwieramy porty (3002 dla Gateway, 50051 dla gRPC, 50052 notify-service gRPC, 50053 gate-service signal gRPC)
EXPOSE 3001 3002 3003 50051 50052 50053

# Domyślna komenda (zostanie nadpisana przez docker-compose)
CMD ["npm", "run", "start:dev"]