version: "3.8"

services:
  # Serwis konfiguracyjny cały systme główny, odpowiedzialny za logikę biznesową, komunikację z bazą danych i innymi serwisami poprzez gRPC oraz udostępnianie API dla frontendu
  bff-service:
    profiles:
      - front
    container_name: bff-service
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npx ts-node-dev -r tsconfig-paths/register --respawn --transpile-only --exit-child src/bff-service/main.ts
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "127.0.0.1:3001:3001"
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      BFF_PORT: 3001
      NOTIFY_SERVICE_GRPC_URL: "notify-service:50052"
      TS_NODE_PROJECT: /app/tsconfig.json
      NODE_OPTIONS: "--max-old-space-size=2048"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      notify-service:
        condition: service_started
        required: false
    networks:
      - backend-net

  # front-servise:
  #   container_name: front-servise
  #   build:
  #     context: ./src/front-servise
  #     dockerfile: Dockerfile.dev
  #   restart: unless-stopped
  #   volumes:
  #     - ./src/front-servise:/app
  #     - /app/node_modules
  #     - /app/.next
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     WATCHPACK_POLLING: true
  #     NEXT_PUBLIC_BFF_URL: "http://bff-service:3001"
  #   depends_on:
  #     - bff-service
  #   networks:
  #     - backend-net

  # Serwis główny, odpowiedzialny za logikę biznesową, komunikację z bazą danych i innymi serwisami poprzez gRPC oraz udostępnianie API dla frontendu
  gate-service:
    container_name: gate-service
    profiles:
      - gate
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped

    # Komenda wymuszająca start konkretnego pliku i obserwowanie zmian
    command: npx ts-node-dev -r tsconfig-paths/register --respawn --transpile-only src/gate-service/main.ts
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "50053:50053"
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      USER_SERVICE_URL: "${GRPC_SERVICE_URL}"
      NOTIFY_SERVICE_GRPC_URL: "notify-service:50052"
      GRPC_PORT: 3002
      SIGNAL_GRPC_PORT: 50053
      TS_NODE_PROJECT: /app/tsconfig.json
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      db-service:
        condition: service_started
      notify-service:
        condition: service_started
    networks:
      - backend-net

    # Database service - serwis odpowiedzialny za komunikację z bazą danych i udostępnianie danych innym serwisom poprzez gRPC
  db-service:
    profiles:
      - gate
      - front
    container_name: db-service
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${GRPC_PORT}:50051"
    command: npx ts-node-dev -r tsconfig-paths/register --respawn --transpile-only src/db-service/main.ts
    restart: unless-stopped
    # Startuje drugi punkt wejścia w tym samym projekcie
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      GRPC_URL: "${GRPC_URL}"
      PROTO_PATH: /app/src/proto/user.proto
      TS_NODE_PROJECT: /app/tsconfig.json
    networks:
      - backend-net
    depends_on:
      postgres:
        condition: service_healthy

  # Serwis powiadamiajacy
  notify-service:
    profiles:
      - gate
      - notify
    container_name: notify-service
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npx ts-node-dev -r tsconfig-paths/register --respawn --transpile-only src/notify-service/main.ts
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "50052:50052"
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      NOTIFY_PORT: 3003
      GRPC_PORT: 50052
      TS_NODE_PROJECT: /app/tsconfig.json
      GATE_SERVICE_GRPC_URL: "gate-service:50053"
      SIGNAL_API_URL: "http://signal_bridge:8080"
      TWILO_SID: "${TWILO_SID}"
      TWILO_TOKEN: "${TWILO_TOKEN}"
      TWILO_PHONE: "${TWILO_PHONE}"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USER: "${SMTP_USER}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SMTP_FROM: "${SMTP_FROM}"
    depends_on:
      signal-api:
        condition: service_started
    networks:
      - backend-net

      # Database

  postgres:
    profiles:
      - gate
      - front
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_DB}"
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Cache i kolejki Redis
  redis:
    profiles:
      - gate
      - front
    environment:
      - REDIS_ARGS=--requirepass "${REDIS_PASSWORD}"
    image: redis/redis-stack-server:latest
    container_name: redis_cache
    restart: unless-stopped
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Most do komunikacji Signal
  signal-api:
    profiles:
      - gate
    image: bbernhard/signal-cli-rest-api
    container_name: signal_bridge
    restart: unless-stopped
    environment:
      - MODE=json-rpc
    volumes:
      - ./signal-data:/home/.local/share/signal-cli
    ports:
      - "8081:8080"
    networks:
      - backend-net

volumes:
  postgres_data:
  redis_data:

networks:
  backend-net:
    driver: bridge
