import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsUUID } from 'class-validator';

export class QrDataDto {
  @ApiProperty({
    description: 'A random UUID used to prevent replay attacks.',
    example: 'a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6',
  })
  @IsUUID()
  @IsNotEmpty()
  nonce: string;

  @ApiProperty({
    description: 'The challenge UUID generated by the server.',
    example: 'a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6',
  })
  @IsUUID()
  @IsNotEmpty()
  challenge: string;
}
