// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v4.25.9
// source: src/proto/bff.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'bff';

export interface ForwardVerificationCodeRequest {
  phoneE164: string;
  code: string;
  /** "signal" | "whatsapp" | "messenger" */
  source: string;
}

export interface BffAck {
  ok: boolean;
}

export const BFF_PACKAGE_NAME = 'bff';

/**
 * Hosted by bff-service — receives push-style notifications from notify-service.
 * Today: forwards verification codes captured from inbound SMS to the frontend
 * over the existing socket.io gateway.
 */

export interface BffNotifyBridgeClient {
  forwardVerificationCode(request: ForwardVerificationCodeRequest, metadata?: Metadata): Observable<BffAck>;
}

/**
 * Hosted by bff-service — receives push-style notifications from notify-service.
 * Today: forwards verification codes captured from inbound SMS to the frontend
 * over the existing socket.io gateway.
 */

export interface BffNotifyBridgeController {
  forwardVerificationCode(
    request: ForwardVerificationCodeRequest,
    metadata?: Metadata,
  ): Promise<BffAck> | Observable<BffAck> | BffAck;
}

export function BffNotifyBridgeControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['forwardVerificationCode'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('BffNotifyBridge', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('BffNotifyBridge', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BFF_NOTIFY_BRIDGE_SERVICE_NAME = 'BffNotifyBridge';
