// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/command.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'command';

export interface RemoveCommandRequest {
  id: string;
}

export interface RemoveCommandResponse {
  status: boolean;
  message: string;
}

/** Message representing a command */
export interface Command {
  id: string;
  name: string;
  description: string;
  active: boolean;
  actions: { [key: string]: boolean };
  parameters: { [key: string]: boolean };
  createdAt: string;
  updatedAt: string;
  roleNames: string[];
}

export interface Command_ActionsEntry {
  key: string;
  value: boolean;
}

export interface Command_ParametersEntry {
  key: string;
  value: boolean;
}

/** Request/Response messages for AddCommand */
export interface AddCommandRequest {
  name: string;
  description: string;
  actions: { [key: string]: boolean };
  parameters: { [key: string]: boolean };
  /** List of role names to grant permissions */
  roleNames: string[];
}

export interface AddCommandRequest_ActionsEntry {
  key: string;
  value: boolean;
}

export interface AddCommandRequest_ParametersEntry {
  key: string;
  value: boolean;
}

/** Request/Response messages for UpdateCommand */
export interface UpdateCommandRequest {
  id: string;
  description?: string | undefined;
  active?: boolean | undefined;
  actions: { [key: string]: boolean };
  /** JSON string */
  parameters: { [key: string]: boolean };
  /** Update permissions (replace existing) */
  roleNames: string[];
}

export interface UpdateCommandRequest_ActionsEntry {
  key: string;
  value: boolean;
}

export interface UpdateCommandRequest_ParametersEntry {
  key: string;
  value: boolean;
}

/** Request/Response messages for GetCommand */
export interface GetCommandRequest {
  id?: string | undefined;
  name?: string | undefined;
}

/** Request/Response messages for GetAllCommands */
export interface GetAllCommandsRequest {
  page: number;
  limit: number;
  activeOnly?: boolean | undefined;
  actionFilter: { [key: string]: boolean };
}

export interface GetAllCommandsRequest_ActionFilterEntry {
  key: string;
  value: boolean;
}

/** Request/Response messages for GetAllByPermission */
export interface GetAllByPermissionRequest {
  roleName: string;
  page: number;
  limit: number;
  activeOnly?: boolean | undefined;
}

/** Request/Response messages for GetByPermission */
export interface GetByPermissionRequest {
  roleName: string;
  id?: string | undefined;
  name?: string | undefined;
}

/** Request/Response messages for ToggleActiveStatus */
export interface ToggleActiveStatusRequest {
  id: string;
  active: boolean;
}

/** Standard response wrapper for single command operations */
export interface CommandResponse {
  status: boolean;
  message: string;
  data?: Command | undefined;
}

/** Response wrapper for multiple commands */
export interface GetAllCommandsResponse {
  status: boolean;
  message: string;
  data: Command[];
  total: number;
  page: number;
  limit: number;
}

export const COMMAND_PACKAGE_NAME = 'command';

export interface CommandServiceClient {
  /** Create a new command */

  addCommand(request: AddCommandRequest, metadata?: Metadata): Observable<CommandResponse>;

  /** remove a new command */

  removeCommand(request: RemoveCommandRequest, metadata?: Metadata): Observable<RemoveCommandResponse>;

  /** Update all fields except the command name */

  updateCommand(request: UpdateCommandRequest, metadata?: Metadata): Observable<CommandResponse>;

  /** Fetch a single command by ID or Name */

  getCommand(request: GetCommandRequest, metadata?: Metadata): Observable<CommandResponse>;

  /** List all commands */

  getAllCommands(request: GetAllCommandsRequest, metadata?: Metadata): Observable<GetAllCommandsResponse>;

  /** Filter commands based on a specific user role/permission */

  getAllByPermission(request: GetAllByPermissionRequest, metadata?: Metadata): Observable<GetAllCommandsResponse>;

  /** Fetch a specific command only if the user has the required permission */

  getByPermission(request: GetByPermissionRequest, metadata?: Metadata): Observable<CommandResponse>;

  /** Change only the active boolean field */

  toggleActiveStatus(request: ToggleActiveStatusRequest, metadata?: Metadata): Observable<CommandResponse>;
}

export interface CommandServiceController {
  /** Create a new command */

  addCommand(
    request: AddCommandRequest,
    metadata?: Metadata,
  ): Promise<CommandResponse> | Observable<CommandResponse> | CommandResponse;

  /** remove a new command */

  removeCommand(
    request: RemoveCommandRequest,
    metadata?: Metadata,
  ): Promise<RemoveCommandResponse> | Observable<RemoveCommandResponse> | RemoveCommandResponse;

  /** Update all fields except the command name */

  updateCommand(
    request: UpdateCommandRequest,
    metadata?: Metadata,
  ): Promise<CommandResponse> | Observable<CommandResponse> | CommandResponse;

  /** Fetch a single command by ID or Name */

  getCommand(
    request: GetCommandRequest,
    metadata?: Metadata,
  ): Promise<CommandResponse> | Observable<CommandResponse> | CommandResponse;

  /** List all commands */

  getAllCommands(
    request: GetAllCommandsRequest,
    metadata?: Metadata,
  ): Promise<GetAllCommandsResponse> | Observable<GetAllCommandsResponse> | GetAllCommandsResponse;

  /** Filter commands based on a specific user role/permission */

  getAllByPermission(
    request: GetAllByPermissionRequest,
    metadata?: Metadata,
  ): Promise<GetAllCommandsResponse> | Observable<GetAllCommandsResponse> | GetAllCommandsResponse;

  /** Fetch a specific command only if the user has the required permission */

  getByPermission(
    request: GetByPermissionRequest,
    metadata?: Metadata,
  ): Promise<CommandResponse> | Observable<CommandResponse> | CommandResponse;

  /** Change only the active boolean field */

  toggleActiveStatus(
    request: ToggleActiveStatusRequest,
    metadata?: Metadata,
  ): Promise<CommandResponse> | Observable<CommandResponse> | CommandResponse;
}

export function CommandServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'addCommand',
      'removeCommand',
      'updateCommand',
      'getCommand',
      'getAllCommands',
      'getAllByPermission',
      'getByPermission',
      'toggleActiveStatus',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('CommandService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('CommandService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const COMMAND_SERVICE_NAME = 'CommandService';
