// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/config.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'config';

/** Configuration entity */
export interface Config {
  id: string;
  key: string;
  value: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}

/** Request to add a new config */
export interface AddConfigRequest {
  key: string;
  value: string;
  description?: string | undefined;
}

/** Request to remove a config by key */
export interface RemoveConfigRequest {
  key: string;
}

/** Request to get a config by key */
export interface GetByKeyRequest {
  key: string;
}

/** Request to get all configs */
export interface GetAllRequest {}

/** Response containing a single config */
export interface ConfigResponse {
  status: boolean;
  message: string;
  data?: Config | undefined;
}

/** Response containing multiple configs */
export interface GetAllResponse {
  status: boolean;
  message: string;
  data: Config[];
}

export const CONFIG_PACKAGE_NAME = 'config';

export interface ConfigServiceClient {
  /** Add a new configuration entry */

  add(request: AddConfigRequest, metadata?: Metadata): Observable<ConfigResponse>;

  /** Remove a configuration entry by key */

  remove(request: RemoveConfigRequest, metadata?: Metadata): Observable<ConfigResponse>;

  /** Get a specific configuration by key */

  getByKey(request: GetByKeyRequest, metadata?: Metadata): Observable<ConfigResponse>;

  /** Get all configuration entries */

  getAll(request: GetAllRequest, metadata?: Metadata): Observable<GetAllResponse>;
}

export interface ConfigServiceController {
  /** Add a new configuration entry */

  add(
    request: AddConfigRequest,
    metadata?: Metadata,
  ): Promise<ConfigResponse> | Observable<ConfigResponse> | ConfigResponse;

  /** Remove a configuration entry by key */

  remove(
    request: RemoveConfigRequest,
    metadata?: Metadata,
  ): Promise<ConfigResponse> | Observable<ConfigResponse> | ConfigResponse;

  /** Get a specific configuration by key */

  getByKey(
    request: GetByKeyRequest,
    metadata?: Metadata,
  ): Promise<ConfigResponse> | Observable<ConfigResponse> | ConfigResponse;

  /** Get all configuration entries */

  getAll(
    request: GetAllRequest,
    metadata?: Metadata,
  ): Promise<GetAllResponse> | Observable<GetAllResponse> | GetAllResponse;
}

export function ConfigServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['add', 'remove', 'getByKey', 'getAll'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('ConfigService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('ConfigService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CONFIG_SERVICE_NAME = 'ConfigService';
