// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.6
// source: src/proto/config.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "../../google/protobuf/empty";

export const protobufPackage = "config";

/** Configuration entity */
export interface Config {
  id: string;
  key: string;
  value: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}

/** Request to add a new config */
export interface UpdateConfigRequest {
  key: string;
  value: string;
}

export interface GetConfigsRequest {
  key: string;
}

/** Response containing multiple configs */
export interface GetAllResponse {
  status: boolean;
  message: string;
  data: Config[];
}

export interface ConfigResponse {
  status: boolean;
  message: string;
  data: Config | undefined;
}

export const CONFIG_PACKAGE_NAME = "config";

export interface ConfigServiceClient {
  getCoreAll(request: Empty, metadata?: Metadata): Observable<GetAllResponse>;

  getFeatures(request: Empty, metadata?: Metadata): Observable<GetAllResponse>;

  getFeatureConfig(request: GetConfigsRequest, metadata?: Metadata): Observable<GetAllResponse>;

  updateConfig(request: UpdateConfigRequest, metadata?: Metadata): Observable<ConfigResponse>;
}

export interface ConfigServiceController {
  getCoreAll(
    request: Empty,
    metadata?: Metadata,
  ): Promise<GetAllResponse> | Observable<GetAllResponse> | GetAllResponse;

  getFeatures(
    request: Empty,
    metadata?: Metadata,
  ): Promise<GetAllResponse> | Observable<GetAllResponse> | GetAllResponse;

  getFeatureConfig(
    request: GetConfigsRequest,
    metadata?: Metadata,
  ): Promise<GetAllResponse> | Observable<GetAllResponse> | GetAllResponse;

  updateConfig(
    request: UpdateConfigRequest,
    metadata?: Metadata,
  ): Promise<ConfigResponse> | Observable<ConfigResponse> | ConfigResponse;
}

export function ConfigServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getCoreAll", "getFeatures", "getFeatureConfig", "updateConfig"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ConfigService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ConfigService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CONFIG_SERVICE_NAME = "ConfigService";
