// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v4.25.9
// source: src/proto/contact-binding.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'contactBinding';

export interface MutationResponse {
  status: boolean;
  message: string;
}

export interface BindingEntry {
  id: string;
  tenantId: string;
  userId: string;
  phoneE164: string;
  token: string;
  /** 'signal' | 'whatsapp' | 'messenger' */
  platform: string;
  /** 'pending' | 'verified' | 'expired' | 'revoked' */
  status: string;
  /** 'operator_frontend' | 'household_invite' */
  source: string;
  /** empty until invite sent */
  outboundMessageId: string;
  /** 'pending' | 'sent' | 'failed' | 'not_on_platform' */
  sendStatus: string;
  /** empty unless send failed */
  sendError: string;
  /** ISO 8601 */
  expiresAt: string;
  /** ISO 8601, empty when not verified */
  verifiedAt: string;
  /** empty when not verified */
  identityId: string;
  createdAt: string;
  updatedAt: string;
}

export interface BindingResponse {
  status: boolean;
  message: string;
  data: BindingEntry | undefined;
}

export interface CreateBindingRequest {
  tenantId: string;
  userId: string;
  phoneE164: string;
  platform: string;
  source: string;
  /** TTL in milliseconds; defaults to 7 days when 0. */
  ttlMs: number;
}

export interface UpdateBindingSendStatusRequest {
  id: string;
  sendStatus: string;
  /** empty unless send succeeded */
  outboundMessageId: string;
  /** empty unless failed */
  sendError: string;
}

/**
 * Atomic: only succeeds when status='pending' AND expires_at > now().
 * On success: status → 'verified', verified_at set, identity_id set to
 * the upserted platform_identities row.
 */
export interface VerifyBindingRequest {
  id: string;
  platformUserId: string;
  /** empty when not known */
  displayName: string;
}

export interface GetBindingRequest {
  id: string;
}

export interface FindBindingByTokenRequest {
  token: string;
  /** When true: only return rows with status='pending' AND expires_at > now(). */
  onlyActive: boolean;
}

export interface FindBindingByOutboundMessageIdRequest {
  outboundMessageId: string;
}

export interface ListPendingBindingsRequest {
  tenantId: string;
}

export interface ListBindingsResponse {
  status: boolean;
  message: string;
  data: BindingEntry[];
}

/**
 * Bulk status flip for the cleanup cron — sets pending rows whose
 * expires_at < now() to 'expired'.
 */
export interface MarkExpiredBindingsRequest {
  /** Cap rows touched per run to keep the cron predictable; 0 = no cap. */
  limit: number;
}

export interface MarkExpiredResponse {
  status: boolean;
  message: string;
  expiredCount: number;
}

export interface RevokeBindingRequest {
  id: string;
}

export interface SendBindingInviteRequest {
  bindingId: string;
  tenantId: string;
  phoneE164: string;
  platform: string;
  token: string;
  /**
   * Optional override for tenant display name in the invite text.
   * Empty = notify-service looks it up from tenants table.
   */
  tenantName: string;
}

export interface SendBindingInviteResponse {
  status: boolean;
  message: string;
  /**
   * signal-cli /v2/send timestamp — caller writes this back via
   * UpdateBindingSendStatus so quote-based detection can match it.
   */
  outboundMessageId: string;
  /** 'pending' | 'sent' | 'failed' | 'not_on_platform' */
  sendStatus: string;
}

export const CONTACT_BINDING_PACKAGE_NAME = 'contactBinding';

/**
 * Hosted by db-service (port 50051) — CRUD over shared_config.contact_bindings.
 * Ephemeral verification flow with 7-day TTL. Created when an operator (or
 * active user adding a household member) invites someone by phone; verified
 * when the recipient replies on Signal — either quoting our outbound message
 * (primary) or repeating the token in plaintext (regex fallback).
 */

export interface ContactBindingDbServiceClient {
  createBinding(request: CreateBindingRequest, metadata?: Metadata): Observable<BindingResponse>;

  updateBindingSendStatus(request: UpdateBindingSendStatusRequest, metadata?: Metadata): Observable<BindingResponse>;

  verifyBinding(request: VerifyBindingRequest, metadata?: Metadata): Observable<BindingResponse>;

  getBinding(request: GetBindingRequest, metadata?: Metadata): Observable<BindingResponse>;

  findBindingByToken(request: FindBindingByTokenRequest, metadata?: Metadata): Observable<BindingResponse>;

  findBindingByOutboundMessageId(
    request: FindBindingByOutboundMessageIdRequest,
    metadata?: Metadata,
  ): Observable<BindingResponse>;

  listPendingBindings(request: ListPendingBindingsRequest, metadata?: Metadata): Observable<ListBindingsResponse>;

  markExpiredBindings(request: MarkExpiredBindingsRequest, metadata?: Metadata): Observable<MarkExpiredResponse>;

  revokeBinding(request: RevokeBindingRequest, metadata?: Metadata): Observable<BindingResponse>;
}

/**
 * Hosted by db-service (port 50051) — CRUD over shared_config.contact_bindings.
 * Ephemeral verification flow with 7-day TTL. Created when an operator (or
 * active user adding a household member) invites someone by phone; verified
 * when the recipient replies on Signal — either quoting our outbound message
 * (primary) or repeating the token in plaintext (regex fallback).
 */

export interface ContactBindingDbServiceController {
  createBinding(
    request: CreateBindingRequest,
    metadata?: Metadata,
  ): Promise<BindingResponse> | Observable<BindingResponse> | BindingResponse;

  updateBindingSendStatus(
    request: UpdateBindingSendStatusRequest,
    metadata?: Metadata,
  ): Promise<BindingResponse> | Observable<BindingResponse> | BindingResponse;

  verifyBinding(
    request: VerifyBindingRequest,
    metadata?: Metadata,
  ): Promise<BindingResponse> | Observable<BindingResponse> | BindingResponse;

  getBinding(
    request: GetBindingRequest,
    metadata?: Metadata,
  ): Promise<BindingResponse> | Observable<BindingResponse> | BindingResponse;

  findBindingByToken(
    request: FindBindingByTokenRequest,
    metadata?: Metadata,
  ): Promise<BindingResponse> | Observable<BindingResponse> | BindingResponse;

  findBindingByOutboundMessageId(
    request: FindBindingByOutboundMessageIdRequest,
    metadata?: Metadata,
  ): Promise<BindingResponse> | Observable<BindingResponse> | BindingResponse;

  listPendingBindings(
    request: ListPendingBindingsRequest,
    metadata?: Metadata,
  ): Promise<ListBindingsResponse> | Observable<ListBindingsResponse> | ListBindingsResponse;

  markExpiredBindings(
    request: MarkExpiredBindingsRequest,
    metadata?: Metadata,
  ): Promise<MarkExpiredResponse> | Observable<MarkExpiredResponse> | MarkExpiredResponse;

  revokeBinding(
    request: RevokeBindingRequest,
    metadata?: Metadata,
  ): Promise<BindingResponse> | Observable<BindingResponse> | BindingResponse;
}

export function ContactBindingDbServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'createBinding',
      'updateBindingSendStatus',
      'verifyBinding',
      'getBinding',
      'findBindingByToken',
      'findBindingByOutboundMessageId',
      'listPendingBindings',
      'markExpiredBindings',
      'revokeBinding',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('ContactBindingDbService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('ContactBindingDbService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CONTACT_BINDING_DB_SERVICE_NAME = 'ContactBindingDbService';

/**
 * Hosted by notify-service (port 50052) — sends the invite over Signal and
 * reports the outbound timestamp back so quote-based detection can match it.
 * Triggered from BFF resolver after CreateBinding succeeded.
 */

export interface ContactBindingNotifyServiceClient {
  sendBindingInvite(request: SendBindingInviteRequest, metadata?: Metadata): Observable<SendBindingInviteResponse>;
}

/**
 * Hosted by notify-service (port 50052) — sends the invite over Signal and
 * reports the outbound timestamp back so quote-based detection can match it.
 * Triggered from BFF resolver after CreateBinding succeeded.
 */

export interface ContactBindingNotifyServiceController {
  sendBindingInvite(
    request: SendBindingInviteRequest,
    metadata?: Metadata,
  ): Promise<SendBindingInviteResponse> | Observable<SendBindingInviteResponse> | SendBindingInviteResponse;
}

export function ContactBindingNotifyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['sendBindingInvite'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('ContactBindingNotifyService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('ContactBindingNotifyService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CONTACT_BINDING_NOTIFY_SERVICE_NAME = 'ContactBindingNotifyService';
