// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/messages.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'messages';

export interface Message {
  key: string;
  value: string;
}

export interface AddMessageRequest {
  key: string;
  value: string;
}

export interface GetMessageRequest {
  key: string;
}

export interface UpdateMessageRequest {
  key: string;
  value: string;
}

export interface RemoveMessageRequest {
  key: string;
}

export interface GetAllMessagesRequest {
  page: number;
  limit: number;
}

export interface MessageResponse {
  status: boolean;
  message: string;
  data?: Message | undefined;
}

export interface GetAllMessagesResponse {
  status: boolean;
  message: string;
  data: Message[];
  total: number;
}

export const MESSAGES_PACKAGE_NAME = 'messages';

export interface MessagesServiceClient {
  addMessage(request: AddMessageRequest, metadata?: Metadata): Observable<MessageResponse>;

  getMessage(request: GetMessageRequest, metadata?: Metadata): Observable<MessageResponse>;

  getAllMessages(request: GetAllMessagesRequest, metadata?: Metadata): Observable<GetAllMessagesResponse>;

  updateMessage(request: UpdateMessageRequest, metadata?: Metadata): Observable<MessageResponse>;

  removeMessage(request: RemoveMessageRequest, metadata?: Metadata): Observable<MessageResponse>;
}

export interface MessagesServiceController {
  addMessage(
    request: AddMessageRequest,
    metadata?: Metadata,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  getMessage(
    request: GetMessageRequest,
    metadata?: Metadata,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  getAllMessages(
    request: GetAllMessagesRequest,
    metadata?: Metadata,
  ): Promise<GetAllMessagesResponse> | Observable<GetAllMessagesResponse> | GetAllMessagesResponse;

  updateMessage(
    request: UpdateMessageRequest,
    metadata?: Metadata,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  removeMessage(
    request: RemoveMessageRequest,
    metadata?: Metadata,
  ): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;
}

export function MessagesServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['addMessage', 'getMessage', 'getAllMessages', 'updateMessage', 'removeMessage'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('MessagesService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('MessagesService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MESSAGES_SERVICE_NAME = 'MessagesService';
