// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/notification.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'notification';

export interface SendSmsRequest {
  phoneNumber: string;
  code: number;
}

export interface SendMailCodeRequest {
  email: string;
  code: number;
}

export interface SendResetTokenRequest {
  email: string;
  url: string;
}

export interface NotificationAck {
  success: boolean;
  message: string;
}

export const NOTIFICATION_PACKAGE_NAME = 'notification';

export interface NotificationServiceClient {
  sendSms(request: SendSmsRequest, metadata?: Metadata): Observable<NotificationAck>;

  sendMailCode(request: SendMailCodeRequest, metadata?: Metadata): Observable<NotificationAck>;

  sendResetToken(request: SendResetTokenRequest, metadata?: Metadata): Observable<NotificationAck>;
}

export interface NotificationServiceController {
  sendSms(
    request: SendSmsRequest,
    metadata?: Metadata,
  ): Promise<NotificationAck> | Observable<NotificationAck> | NotificationAck;

  sendMailCode(
    request: SendMailCodeRequest,
    metadata?: Metadata,
  ): Promise<NotificationAck> | Observable<NotificationAck> | NotificationAck;

  sendResetToken(
    request: SendResetTokenRequest,
    metadata?: Metadata,
  ): Promise<NotificationAck> | Observable<NotificationAck> | NotificationAck;
}

export function NotificationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['sendSms', 'sendMailCode', 'sendResetToken'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('NotificationService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('NotificationService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const NOTIFICATION_SERVICE_NAME = 'NotificationService';
