// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/notify.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'notify';

export enum Platform {
  Signal = 0,
  Whatsapp = 1,
  Messenger = 2,
  Sms = 3,
  Email = 4,
  UNRECOGNIZED = -1,
}

export enum Type {
  Text = 0,
  Image = 2,
  Audio = 3,
  Poll = 4,
  MessageReaction = 5,
  UNRECOGNIZED = -1,
}

/** Full SignalMessage serialized as JSON — preserves the complete, unmodified structure */
export interface OutgoingNotifyRequest {
  platforms: Platform[];
  message: UnifiedMessage | undefined;
}

/** Outbound message from gate-service to be sent via Signal */
export interface IncomingNotifyRequest {
  status: boolean;
  message: string;
  data: UnifiedMessage | undefined;
}

export interface UnifiedMessage {
  platform: Platform;
  chatId: string;
  authorId: string;
  messageId: string;
  isGroup?: boolean | undefined;
  groupName?: string | undefined;
  type: Type;
  content?: string | undefined;
  media?: Media | undefined;
  poll?: Pool | undefined;
  reaction?: Reaction | undefined;
  raw: string;
}

export interface Media {
  url: string;
  contentType: string;
  data?: Uint8Array | undefined;
  duration?: number | undefined;
}

export interface Pool {
  question: string;
  options: Options[];
}

export interface Options {
  id: string;
  text: string;
}

export interface Reaction {
  emoji: string;
  targetMessageId: string;
}

export interface SendVerificationCodeRequest {
  platforms: Platform[];
  code: number;
  phoneNumber?: string | undefined;
  email?: string | undefined;
}

export interface SendTokenRequest {
  platforms: Platform[];
  email: string;
  url: string;
}

export interface NotifyAck {
  success: boolean;
  message: string;
}

export const NOTIFY_PACKAGE_NAME = 'notify';

/** Hosted by gate-service (port 50053) — receives incoming Signal messages from notify-service */

export interface IncomingNotifyServiceClient {
  receiveMessage(request: IncomingNotifyRequest, metadata?: Metadata): Observable<NotifyAck>;
}

/** Hosted by gate-service (port 50053) — receives incoming Signal messages from notify-service */

export interface IncomingNotifyServiceController {
  receiveMessage(
    request: IncomingNotifyRequest,
    metadata?: Metadata,
  ): Promise<NotifyAck> | Observable<NotifyAck> | NotifyAck;
}

export function IncomingNotifyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['receiveMessage'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('IncomingNotifyService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('IncomingNotifyService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const INCOMING_NOTIFY_SERVICE_NAME = 'IncomingNotifyService';

/** Hosted by notify-service (port 50052) — receives outbound send requests from gate-service */

export interface OutgoingNotifyServiceClient {
  sendMessage(request: OutgoingNotifyRequest, metadata?: Metadata): Observable<NotifyAck>;

  sendVerificationCode(request: SendVerificationCodeRequest, metadata?: Metadata): Observable<NotifyAck>;

  sendToken(request: SendTokenRequest, metadata?: Metadata): Observable<NotifyAck>;
}

/** Hosted by notify-service (port 50052) — receives outbound send requests from gate-service */

export interface OutgoingNotifyServiceController {
  sendMessage(
    request: OutgoingNotifyRequest,
    metadata?: Metadata,
  ): Promise<NotifyAck> | Observable<NotifyAck> | NotifyAck;

  sendVerificationCode(
    request: SendVerificationCodeRequest,
    metadata?: Metadata,
  ): Promise<NotifyAck> | Observable<NotifyAck> | NotifyAck;

  sendToken(request: SendTokenRequest, metadata?: Metadata): Promise<NotifyAck> | Observable<NotifyAck> | NotifyAck;
}

export function OutgoingNotifyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['sendMessage', 'sendVerificationCode', 'sendToken'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('OutgoingNotifyService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('OutgoingNotifyService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const OUTGOING_NOTIFY_SERVICE_NAME = 'OutgoingNotifyService';
