// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/onboarding.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'onboarding';

export interface StartOnboardingRequest {
  /**
   * Empty when a wizard creates credentials before the tenant exists.
   * Required when intent='replace' (settings flow).
   */
  tenantId?: string | undefined;
  /**
   * 'signal' | 'whatsapp' | 'messenger' | ... — string, not enum, so a new
   * platform doesn't require a contract redeploy.
   */
  platform: string;
  /** Platform-specific JSON payload (e.g. for signal: { apiUrl, account, mode, intent, previousAccount }). */
  paramsJson: string;
}

export interface SubmitOnboardingRequest {
  sessionId: string;
  /**
   * The step the client is responding to. Must equal the stepKey returned in
   * the previous OnboardingStepResponse — guards against out-of-order submits.
   */
  stepKey: string;
  /** Step-specific payload JSON (captcha token, verification code, etc.). */
  payloadJson: string;
}

export interface CancelOnboardingRequest {
  sessionId: string;
}

export interface OnboardingStepResponse {
  success: boolean;
  sessionId: string;
  /** 'form' | 'qrcode' | 'captcha' | 'verification_code' | 'info' | 'done' | 'error' */
  stepType: string;
  /** Identifies which step the next submit must address. */
  stepKey: string;
  /** Step-type-specific JSON payload (qr image, captcha url, credentials json, ...). */
  dataJson: string;
  error: string;
}

export interface OnboardingAck {
  success: boolean;
  message: string;
}

export const ONBOARDING_PACKAGE_NAME = 'onboarding';

/**
 * Hosted by notify-service (port 50052) — drives multi-step platform onboarding
 * flows (e.g. Signal phone registration / device-link). Per-platform logic lives
 * behind an OnboardingProvider; this contract is intentionally generic so new
 * platforms can register their own flow without changing the wire format.
 */

export interface PlatformOnboardingServiceClient {
  startOnboarding(request: StartOnboardingRequest, metadata?: Metadata): Observable<OnboardingStepResponse>;

  submitOnboarding(request: SubmitOnboardingRequest, metadata?: Metadata): Observable<OnboardingStepResponse>;

  cancelOnboarding(request: CancelOnboardingRequest, metadata?: Metadata): Observable<OnboardingAck>;
}

/**
 * Hosted by notify-service (port 50052) — drives multi-step platform onboarding
 * flows (e.g. Signal phone registration / device-link). Per-platform logic lives
 * behind an OnboardingProvider; this contract is intentionally generic so new
 * platforms can register their own flow without changing the wire format.
 */

export interface PlatformOnboardingServiceController {
  startOnboarding(
    request: StartOnboardingRequest,
    metadata?: Metadata,
  ): Promise<OnboardingStepResponse> | Observable<OnboardingStepResponse> | OnboardingStepResponse;

  submitOnboarding(
    request: SubmitOnboardingRequest,
    metadata?: Metadata,
  ): Promise<OnboardingStepResponse> | Observable<OnboardingStepResponse> | OnboardingStepResponse;

  cancelOnboarding(
    request: CancelOnboardingRequest,
    metadata?: Metadata,
  ): Promise<OnboardingAck> | Observable<OnboardingAck> | OnboardingAck;
}

export function PlatformOnboardingServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['startOnboarding', 'submitOnboarding', 'cancelOnboarding'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('PlatformOnboardingService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('PlatformOnboardingService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PLATFORM_ONBOARDING_SERVICE_NAME = 'PlatformOnboardingService';
