// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.6
// source: src/proto/passkey.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "passkey";

export interface RemovePasskeyRequest {
  id: string;
}

export interface PasskeyResponse {
  success: boolean;
  message: string;
}

export interface AddPasskeyRequest {
  credentialID: string;
  publicKey: Uint8Array;
  deviceName: string;
  userId: string;
}

export interface GetPasskeyRequest {
  credentialID: string;
}

export interface GetPasskeysRequest {
  userId: string;
}

export interface GetPasskeyResponse {
  success: boolean;
  message: string;
  userId?: string | undefined;
  credentialID?: string | undefined;
  publicKey?: Uint8Array | undefined;
  counter?: number | undefined;
}

export interface Passkey {
  id: string;
  createAt: string;
  deviceName: string;
  credentialID: string;
}

export interface GetPasskeysResponse {
  passkeys: Passkey[];
}

export interface SetCounterRequest {
  credentialID: string;
  counter: number;
}

export const PASSKEY_PACKAGE_NAME = "passkey";

export interface PasskeyProxyServiceClient {
  removePasskey(request: RemovePasskeyRequest, metadata?: Metadata): Observable<PasskeyResponse>;

  addPasskey(request: AddPasskeyRequest, metadata?: Metadata): Observable<PasskeyResponse>;

  getPasskey(request: GetPasskeyRequest, metadata?: Metadata): Observable<GetPasskeyResponse>;

  getPasskeys(request: GetPasskeysRequest, metadata?: Metadata): Observable<GetPasskeysResponse>;

  setCounter(request: SetCounterRequest, metadata?: Metadata): Observable<PasskeyResponse>;
}

export interface PasskeyProxyServiceController {
  removePasskey(
    request: RemovePasskeyRequest,
    metadata?: Metadata,
  ): Promise<PasskeyResponse> | Observable<PasskeyResponse> | PasskeyResponse;

  addPasskey(
    request: AddPasskeyRequest,
    metadata?: Metadata,
  ): Promise<PasskeyResponse> | Observable<PasskeyResponse> | PasskeyResponse;

  getPasskey(
    request: GetPasskeyRequest,
    metadata?: Metadata,
  ): Promise<GetPasskeyResponse> | Observable<GetPasskeyResponse> | GetPasskeyResponse;

  getPasskeys(
    request: GetPasskeysRequest,
    metadata?: Metadata,
  ): Promise<GetPasskeysResponse> | Observable<GetPasskeysResponse> | GetPasskeysResponse;

  setCounter(
    request: SetCounterRequest,
    metadata?: Metadata,
  ): Promise<PasskeyResponse> | Observable<PasskeyResponse> | PasskeyResponse;
}

export function PasskeyProxyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["removePasskey", "addPasskey", "getPasskey", "getPasskeys", "setCounter"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PasskeyProxyService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PasskeyProxyService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PASSKEY_PROXY_SERVICE_NAME = "PasskeyProxyService";
