// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.6
// source: src/proto/phone-procurement.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'phoneProcurement';

export interface MutationResponse {
  status: boolean;
  message: string;
}

export interface TenantPhoneNumberEntry {
  id: string;
  tenantId: string;
  phoneE164: string;
  providerKey: string;
  providerExternalId: string;
  /** 'managed' | 'self' */
  provisionedBy: string;
  monthlyMessageCount: number;
  /** ISO 8601 timestamp; empty when never synced. */
  lastSyncedAt: string;
  /** ISO 8601 timestamp. */
  purchasedAt: string;
}

export interface GetTenantPhoneNumberByE164Request {
  phoneE164: string;
}

export interface GetTenantPhoneNumberRequest {
  tenantId: string;
}

export interface GetTenantPhoneNumberResponse {
  status: boolean;
  message: string;
  /** Empty when no row matched. */
  entry: TenantPhoneNumberEntry | undefined;
}

export interface ListManagedPhoneNumbersRequest {}

export interface ListManagedPhoneNumbersResponse {
  status: boolean;
  message: string;
  entries: TenantPhoneNumberEntry[];
}

export interface IncrementMonthlyMessageCountRequest {
  tenantId: string;
  delta: number;
  /** ISO 8601 timestamp — written to last_synced_at. */
  syncedAt: string;
}

export interface ResetAllMonthlyMessageCountsRequest {}

export interface HasSmsSyncLogForDateRequest {
  tenantId: string;
  /** ISO date 'YYYY-MM-DD' (UTC). */
  syncDate: string;
}

export interface HasSmsSyncLogForDateResponse {
  status: boolean;
  message: string;
  exists: boolean;
}

export interface InsertSmsSyncLogRequest {
  tenantId: string;
  syncDate: string;
  messagesCounted: number;
}

export interface PendingPurchaseEntry {
  id: string;
  ownerUserId: string;
  providerKey: string;
  providerExternalId: string;
  phoneE164: string;
  /** Empty when not yet attached. */
  attachedToTenantId: string;
  purchasedAt: string;
  /** Empty when not yet attached. */
  attachedAt: string;
}

export interface PendingPurchaseResponse {
  status: boolean;
  message: string;
  entry: PendingPurchaseEntry | undefined;
}

export interface InsertPendingPurchaseRequest {
  ownerUserId: string;
  providerKey: string;
  providerExternalId: string;
  phoneE164: string;
}

export interface AttachPendingPurchaseToTenantRequest {
  pendingId: string;
  tenantId: string;
  /** 'managed' | 'self'. Determines tenant_phone_numbers.provisioned_by. */
  provisionedBy: string;
}

export interface DeletePendingPurchaseRequest {
  pendingId: string;
}

export interface GetPendingPurchaseRequest {
  pendingId: string;
}

export interface ListUnattachedPendingPurchasesRequest {
  /** ISO 8601 timestamp — only return rows with purchased_at < cutoff_iso. */
  cutoffIso: string;
}

export interface ListUnattachedPendingPurchasesResponse {
  status: boolean;
  message: string;
  entries: PendingPurchaseEntry[];
}

export interface PhoneCapabilitiesEntry {
  sms: boolean;
  mms: boolean;
  voice: boolean;
}

export interface AvailablePhoneNumberEntry {
  phoneE164: string;
  capabilities: PhoneCapabilitiesEntry | undefined;
  region: string;
  locality: string;
}

export interface ListAvailableNumbersRequest {
  /** ISO 3166-1 alpha-2 country code: 'PL', 'DE', 'US', ... */
  country: string;
  /** 'mobile' | 'local' | 'tollfree'. Empty defaults to 'mobile'. */
  type: string;
  limit: number;
}

export interface ListAvailableNumbersResponse {
  status: boolean;
  message: string;
  numbers: AvailablePhoneNumberEntry[];
}

export interface PurchasePhoneNumberRequest {
  /** Authenticated user driving the wizard — owns the pending row until attach. */
  ownerUserId: string;
  country: string;
  phoneE164: string;
}

export interface ReleasePendingPurchaseRequest {
  pendingId: string;
  /**
   * Caller (BFF) checks ownership before invoking; the notify side trusts
   * the request for now.
   */
  ownerUserId: string;
}

export interface GetActiveProviderInfoRequest {}

export interface GetActiveProviderInfoResponse {
  status: boolean;
  providerKey: string;
  isSandbox: boolean;
}

export interface GetSignalVerificationCodeRequest {
  phoneE164: string;
}

export interface GetSignalVerificationCodeResponse {
  status: boolean;
  /** Empty when no code recorded yet (poll again). */
  code: string;
  /** ISO 8601 timestamp; empty when no code recorded. */
  receivedAt: string;
}

export const PHONE_PROCUREMENT_PACKAGE_NAME = 'phoneProcurement';

/**
 * Hosted by db-service (port 50051) — CRUD over tenant_phone_numbers,
 * pending_phone_purchases and sms_sync_log. Consumed by:
 *   - notify-service Twilio webhook (tenant lookup by E.164)
 *   - notify-service crons (counter sync, stale-purchase cleanup)
 *   - bff-service phone-procurement resolver (purchase / attach / release)
 *
 * Provider-agnostic by design — providerKey + providerExternalId are
 * opaque strings. The active provider lives in notify-service.
 */

export interface PhoneProcurementDbServiceClient {
  /** --- tenant_phone_numbers --- */

  getTenantPhoneNumberByE164(
    request: GetTenantPhoneNumberByE164Request,
    metadata?: Metadata,
  ): Observable<GetTenantPhoneNumberResponse>;

  getTenantPhoneNumber(
    request: GetTenantPhoneNumberRequest,
    metadata?: Metadata,
  ): Observable<GetTenantPhoneNumberResponse>;

  listManagedPhoneNumbers(
    request: ListManagedPhoneNumbersRequest,
    metadata?: Metadata,
  ): Observable<ListManagedPhoneNumbersResponse>;

  incrementMonthlyMessageCount(
    request: IncrementMonthlyMessageCountRequest,
    metadata?: Metadata,
  ): Observable<MutationResponse>;

  resetAllMonthlyMessageCounts(
    request: ResetAllMonthlyMessageCountsRequest,
    metadata?: Metadata,
  ): Observable<MutationResponse>;

  /** --- sms_sync_log --- */

  hasSmsSyncLogForDate(
    request: HasSmsSyncLogForDateRequest,
    metadata?: Metadata,
  ): Observable<HasSmsSyncLogForDateResponse>;

  insertSmsSyncLog(request: InsertSmsSyncLogRequest, metadata?: Metadata): Observable<MutationResponse>;

  /** --- pending_phone_purchases --- */

  insertPendingPurchase(
    request: InsertPendingPurchaseRequest,
    metadata?: Metadata,
  ): Observable<PendingPurchaseResponse>;

  attachPendingPurchaseToTenant(
    request: AttachPendingPurchaseToTenantRequest,
    metadata?: Metadata,
  ): Observable<PendingPurchaseResponse>;

  deletePendingPurchase(request: DeletePendingPurchaseRequest, metadata?: Metadata): Observable<MutationResponse>;

  listUnattachedPendingPurchases(
    request: ListUnattachedPendingPurchasesRequest,
    metadata?: Metadata,
  ): Observable<ListUnattachedPendingPurchasesResponse>;

  getPendingPurchase(request: GetPendingPurchaseRequest, metadata?: Metadata): Observable<PendingPurchaseResponse>;
}

/**
 * Hosted by db-service (port 50051) — CRUD over tenant_phone_numbers,
 * pending_phone_purchases and sms_sync_log. Consumed by:
 *   - notify-service Twilio webhook (tenant lookup by E.164)
 *   - notify-service crons (counter sync, stale-purchase cleanup)
 *   - bff-service phone-procurement resolver (purchase / attach / release)
 *
 * Provider-agnostic by design — providerKey + providerExternalId are
 * opaque strings. The active provider lives in notify-service.
 */

export interface PhoneProcurementDbServiceController {
  /** --- tenant_phone_numbers --- */

  getTenantPhoneNumberByE164(
    request: GetTenantPhoneNumberByE164Request,
    metadata?: Metadata,
  ): Promise<GetTenantPhoneNumberResponse> | Observable<GetTenantPhoneNumberResponse> | GetTenantPhoneNumberResponse;

  getTenantPhoneNumber(
    request: GetTenantPhoneNumberRequest,
    metadata?: Metadata,
  ): Promise<GetTenantPhoneNumberResponse> | Observable<GetTenantPhoneNumberResponse> | GetTenantPhoneNumberResponse;

  listManagedPhoneNumbers(
    request: ListManagedPhoneNumbersRequest,
    metadata?: Metadata,
  ):
    | Promise<ListManagedPhoneNumbersResponse>
    | Observable<ListManagedPhoneNumbersResponse>
    | ListManagedPhoneNumbersResponse;

  incrementMonthlyMessageCount(
    request: IncrementMonthlyMessageCountRequest,
    metadata?: Metadata,
  ): Promise<MutationResponse> | Observable<MutationResponse> | MutationResponse;

  resetAllMonthlyMessageCounts(
    request: ResetAllMonthlyMessageCountsRequest,
    metadata?: Metadata,
  ): Promise<MutationResponse> | Observable<MutationResponse> | MutationResponse;

  /** --- sms_sync_log --- */

  hasSmsSyncLogForDate(
    request: HasSmsSyncLogForDateRequest,
    metadata?: Metadata,
  ): Promise<HasSmsSyncLogForDateResponse> | Observable<HasSmsSyncLogForDateResponse> | HasSmsSyncLogForDateResponse;

  insertSmsSyncLog(
    request: InsertSmsSyncLogRequest,
    metadata?: Metadata,
  ): Promise<MutationResponse> | Observable<MutationResponse> | MutationResponse;

  /** --- pending_phone_purchases --- */

  insertPendingPurchase(
    request: InsertPendingPurchaseRequest,
    metadata?: Metadata,
  ): Promise<PendingPurchaseResponse> | Observable<PendingPurchaseResponse> | PendingPurchaseResponse;

  attachPendingPurchaseToTenant(
    request: AttachPendingPurchaseToTenantRequest,
    metadata?: Metadata,
  ): Promise<PendingPurchaseResponse> | Observable<PendingPurchaseResponse> | PendingPurchaseResponse;

  deletePendingPurchase(
    request: DeletePendingPurchaseRequest,
    metadata?: Metadata,
  ): Promise<MutationResponse> | Observable<MutationResponse> | MutationResponse;

  listUnattachedPendingPurchases(
    request: ListUnattachedPendingPurchasesRequest,
    metadata?: Metadata,
  ):
    | Promise<ListUnattachedPendingPurchasesResponse>
    | Observable<ListUnattachedPendingPurchasesResponse>
    | ListUnattachedPendingPurchasesResponse;

  getPendingPurchase(
    request: GetPendingPurchaseRequest,
    metadata?: Metadata,
  ): Promise<PendingPurchaseResponse> | Observable<PendingPurchaseResponse> | PendingPurchaseResponse;
}

export function PhoneProcurementDbServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getTenantPhoneNumberByE164',
      'getTenantPhoneNumber',
      'listManagedPhoneNumbers',
      'incrementMonthlyMessageCount',
      'resetAllMonthlyMessageCounts',
      'hasSmsSyncLogForDate',
      'insertSmsSyncLog',
      'insertPendingPurchase',
      'attachPendingPurchaseToTenant',
      'deletePendingPurchase',
      'listUnattachedPendingPurchases',
      'getPendingPurchase',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('PhoneProcurementDbService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('PhoneProcurementDbService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PHONE_PROCUREMENT_DB_SERVICE_NAME = 'PhoneProcurementDbService';

/**
 * Hosted by notify-service (port 50052) — wraps the active phone provider
 * (Twilio / mock sandbox) and the matching pending-purchase bookkeeping
 * in db-service so callers (BFF resolver) get an atomic "buy + persist"
 * or "release + delete" operation.
 */

export interface PhoneProcurementNotifyServiceClient {
  listAvailableNumbers(
    request: ListAvailableNumbersRequest,
    metadata?: Metadata,
  ): Observable<ListAvailableNumbersResponse>;

  purchasePhoneNumber(request: PurchasePhoneNumberRequest, metadata?: Metadata): Observable<PendingPurchaseResponse>;

  releasePendingPurchase(request: ReleasePendingPurchaseRequest, metadata?: Metadata): Observable<MutationResponse>;

  getActiveProviderInfo(
    request: GetActiveProviderInfoRequest,
    metadata?: Metadata,
  ): Observable<GetActiveProviderInfoResponse>;

  /**
   * Reads a Signal verification code stashed by the Twilio webhook so the
   * wizard frontend can auto-fill the verifyCode step without the user
   * ever seeing the SMS body. Caller-side authorization (BFF resolver
   * verifies the phone belongs to the calling user via pending purchase
   * or tenant phone numbers).
   */

  getSignalVerificationCode(
    request: GetSignalVerificationCodeRequest,
    metadata?: Metadata,
  ): Observable<GetSignalVerificationCodeResponse>;
}

/**
 * Hosted by notify-service (port 50052) — wraps the active phone provider
 * (Twilio / mock sandbox) and the matching pending-purchase bookkeeping
 * in db-service so callers (BFF resolver) get an atomic "buy + persist"
 * or "release + delete" operation.
 */

export interface PhoneProcurementNotifyServiceController {
  listAvailableNumbers(
    request: ListAvailableNumbersRequest,
    metadata?: Metadata,
  ): Promise<ListAvailableNumbersResponse> | Observable<ListAvailableNumbersResponse> | ListAvailableNumbersResponse;

  purchasePhoneNumber(
    request: PurchasePhoneNumberRequest,
    metadata?: Metadata,
  ): Promise<PendingPurchaseResponse> | Observable<PendingPurchaseResponse> | PendingPurchaseResponse;

  releasePendingPurchase(
    request: ReleasePendingPurchaseRequest,
    metadata?: Metadata,
  ): Promise<MutationResponse> | Observable<MutationResponse> | MutationResponse;

  getActiveProviderInfo(
    request: GetActiveProviderInfoRequest,
    metadata?: Metadata,
  ): Promise<GetActiveProviderInfoResponse> | Observable<GetActiveProviderInfoResponse> | GetActiveProviderInfoResponse;

  /**
   * Reads a Signal verification code stashed by the Twilio webhook so the
   * wizard frontend can auto-fill the verifyCode step without the user
   * ever seeing the SMS body. Caller-side authorization (BFF resolver
   * verifies the phone belongs to the calling user via pending purchase
   * or tenant phone numbers).
   */

  getSignalVerificationCode(
    request: GetSignalVerificationCodeRequest,
    metadata?: Metadata,
  ):
    | Promise<GetSignalVerificationCodeResponse>
    | Observable<GetSignalVerificationCodeResponse>
    | GetSignalVerificationCodeResponse;
}

export function PhoneProcurementNotifyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'listAvailableNumbers',
      'purchasePhoneNumber',
      'releasePendingPurchase',
      'getActiveProviderInfo',
      'getSignalVerificationCode',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('PhoneProcurementNotifyService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('PhoneProcurementNotifyService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PHONE_PROCUREMENT_NOTIFY_SERVICE_NAME = 'PhoneProcurementNotifyService';
