// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v4.25.9
// source: src/proto/platform-identity.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'platformIdentity';

export interface MutationResponse {
  status: boolean;
  message: string;
}

export interface PlatformIdentityEntry {
  id: string;
  tenantId: string;
  userId: string;
  /** 'signal' | 'whatsapp' | 'messenger' */
  platform: string;
  platformUserId: string;
  /** empty when not known */
  phoneE164: string;
  /** empty when not known */
  displayName: string;
  /** ISO 8601 */
  verifiedAt: string;
  /** ISO 8601, empty when never seen */
  lastSeenAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface PlatformIdentityResponse {
  status: boolean;
  message: string;
  data: PlatformIdentityEntry | undefined;
}

export interface UpsertPlatformIdentityRequest {
  tenantId: string;
  userId: string;
  platform: string;
  platformUserId: string;
  /** empty when not known */
  phoneE164: string;
  /** empty when not known */
  displayName: string;
  /** ISO 8601 */
  verifiedAt: string;
}

export interface FindByPlatformUserIdRequest {
  tenantId: string;
  platform: string;
  platformUserId: string;
}

/**
 * Lightweight lookup used on every incoming Signal message — returns
 * just enough to translate UUID → phone for the existing identity flow.
 */
export interface ResolvePhoneRequest {
  tenantId: string;
  platform: string;
  platformUserId: string;
}

export interface ResolvePhoneResponse {
  found: boolean;
  /** empty when found=false */
  phoneE164: string;
  /** empty when found=false */
  userId: string;
}

export interface ListByUserRequest {
  userId: string;
}

export interface ListPlatformIdentitiesResponse {
  status: boolean;
  message: string;
  data: PlatformIdentityEntry[];
}

export interface UpdateLastSeenRequest {
  id: string;
  /** ISO 8601 */
  seenAt: string;
}

/**
 * Move an identity row from one user to another. Used when the same Signal
 * UUID is re-bound to a different User in the same tenant (user changed
 * their phone but kept their Signal account).
 */
export interface TransferIdentityRequest {
  id: string;
  newUserId: string;
  /** empty to keep existing */
  newPhoneE164: string;
}

export const PLATFORM_IDENTITY_PACKAGE_NAME = 'platformIdentity';

/**
 * Hosted by db-service (port 50051) — CRUD over shared_config.platform_identities.
 * Source of truth for "who is this Signal UUID / WA jid / FB id?" lookups.
 * Queried by signal-transformer on every incoming Signal message
 * (UUID → phone resolution) so the existing core-service identity handler
 * (lookup by phone) keeps working unchanged.
 */

export interface PlatformIdentityDbServiceClient {
  upsertPlatformIdentity(
    request: UpsertPlatformIdentityRequest,
    metadata?: Metadata,
  ): Observable<PlatformIdentityResponse>;

  findByPlatformUserId(request: FindByPlatformUserIdRequest, metadata?: Metadata): Observable<PlatformIdentityResponse>;

  resolvePhoneByPlatformUserId(request: ResolvePhoneRequest, metadata?: Metadata): Observable<ResolvePhoneResponse>;

  listByUser(request: ListByUserRequest, metadata?: Metadata): Observable<ListPlatformIdentitiesResponse>;

  updateLastSeen(request: UpdateLastSeenRequest, metadata?: Metadata): Observable<MutationResponse>;

  transferIdentity(request: TransferIdentityRequest, metadata?: Metadata): Observable<PlatformIdentityResponse>;
}

/**
 * Hosted by db-service (port 50051) — CRUD over shared_config.platform_identities.
 * Source of truth for "who is this Signal UUID / WA jid / FB id?" lookups.
 * Queried by signal-transformer on every incoming Signal message
 * (UUID → phone resolution) so the existing core-service identity handler
 * (lookup by phone) keeps working unchanged.
 */

export interface PlatformIdentityDbServiceController {
  upsertPlatformIdentity(
    request: UpsertPlatformIdentityRequest,
    metadata?: Metadata,
  ): Promise<PlatformIdentityResponse> | Observable<PlatformIdentityResponse> | PlatformIdentityResponse;

  findByPlatformUserId(
    request: FindByPlatformUserIdRequest,
    metadata?: Metadata,
  ): Promise<PlatformIdentityResponse> | Observable<PlatformIdentityResponse> | PlatformIdentityResponse;

  resolvePhoneByPlatformUserId(
    request: ResolvePhoneRequest,
    metadata?: Metadata,
  ): Promise<ResolvePhoneResponse> | Observable<ResolvePhoneResponse> | ResolvePhoneResponse;

  listByUser(
    request: ListByUserRequest,
    metadata?: Metadata,
  ):
    | Promise<ListPlatformIdentitiesResponse>
    | Observable<ListPlatformIdentitiesResponse>
    | ListPlatformIdentitiesResponse;

  updateLastSeen(
    request: UpdateLastSeenRequest,
    metadata?: Metadata,
  ): Promise<MutationResponse> | Observable<MutationResponse> | MutationResponse;

  transferIdentity(
    request: TransferIdentityRequest,
    metadata?: Metadata,
  ): Promise<PlatformIdentityResponse> | Observable<PlatformIdentityResponse> | PlatformIdentityResponse;
}

export function PlatformIdentityDbServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'upsertPlatformIdentity',
      'findByPlatformUserId',
      'resolvePhoneByPlatformUserId',
      'listByUser',
      'updateLastSeen',
      'transferIdentity',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('PlatformIdentityDbService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('PlatformIdentityDbService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PLATFORM_IDENTITY_DB_SERVICE_NAME = 'PlatformIdentityDbService';
