// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/prompt.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'prompt';

export enum UserType {
  OWNER = 0,
  ADMIN = 1,
  SUPER_USER = 2,
  MEMBER = 3,
  USER = 4,
  UNRECOGNIZED = -1,
}

export interface AddPromptRequest {
  userType: UserType;
  prompt: string;
  key: string;
  description: string;
  commandName: string;
}

export interface GetPromptByIdRequest {
  id: string;
}

export interface GetPromptByKeyRequest {
  key: string;
}

export interface UpdatePromptRequest {
  id: string;
  key?: string | undefined;
  description?: string | undefined;
  commandName?: string | undefined;
  userType?: UserType | undefined;
  prompt?: string | undefined;
}

export interface RemovePromptRequest {
  id: string;
}

export interface GetAllPromptsRequest {
  page: number;
  limit: number;
  userType?: UserType | undefined;
}

export interface PromptResponse {
  status: boolean;
  message: string;
  data?: Prompt | undefined;
}

export interface GetAllPromptsResponse {
  status: boolean;
  message: string;
  data: PromptSimply[];
  total: number;
}

export interface PromptSimply {
  id: string;
  key: string;
  description: string;
  commandName: string;
  userType: UserType;
}

export interface Prompt {
  id: string;
  key: string;
  description: string;
  commandName: string;
  userType: UserType;
  prompt: string;
}

export const PROMPT_PACKAGE_NAME = 'prompt';

export interface PromptProxyServiceClient {
  addPrompt(request: AddPromptRequest, metadata?: Metadata): Observable<PromptResponse>;

  getPromptById(request: GetPromptByIdRequest, metadata?: Metadata): Observable<PromptResponse>;

  getPromptByKey(request: GetPromptByKeyRequest, metadata?: Metadata): Observable<PromptResponse>;

  updatePrompt(request: UpdatePromptRequest, metadata?: Metadata): Observable<PromptResponse>;

  removePrompt(request: RemovePromptRequest, metadata?: Metadata): Observable<PromptResponse>;

  getAllPrompts(request: GetAllPromptsRequest, metadata?: Metadata): Observable<GetAllPromptsResponse>;
}

export interface PromptProxyServiceController {
  addPrompt(
    request: AddPromptRequest,
    metadata?: Metadata,
  ): Promise<PromptResponse> | Observable<PromptResponse> | PromptResponse;

  getPromptById(
    request: GetPromptByIdRequest,
    metadata?: Metadata,
  ): Promise<PromptResponse> | Observable<PromptResponse> | PromptResponse;

  getPromptByKey(
    request: GetPromptByKeyRequest,
    metadata?: Metadata,
  ): Promise<PromptResponse> | Observable<PromptResponse> | PromptResponse;

  updatePrompt(
    request: UpdatePromptRequest,
    metadata?: Metadata,
  ): Promise<PromptResponse> | Observable<PromptResponse> | PromptResponse;

  removePrompt(
    request: RemovePromptRequest,
    metadata?: Metadata,
  ): Promise<PromptResponse> | Observable<PromptResponse> | PromptResponse;

  getAllPrompts(
    request: GetAllPromptsRequest,
    metadata?: Metadata,
  ): Promise<GetAllPromptsResponse> | Observable<GetAllPromptsResponse> | GetAllPromptsResponse;
}

export function PromptProxyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'addPrompt',
      'getPromptById',
      'getPromptByKey',
      'updatePrompt',
      'removePrompt',
      'getAllPrompts',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('PromptProxyService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('PromptProxyService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PROMPT_PROXY_SERVICE_NAME = 'PromptProxyService';
