// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/risk.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "risk";

export interface FailureRequest {
  id: string;
  fingerprintHash: string;
}

export interface LogRiskEventRequest {
  userId: string;
  city: string;
  country: string;
  lastIp: string;
  fingerprintHash: string;
  userAgent: string;
}

export interface EventResponse {
  success: boolean;
  message?: string | undefined;
}

export interface UpdateRiskEventRequest {
  userId: string;
  city: string;
  country: string;
  lastIp: string;
  fingerprintHash: string;
  userAgent: string;
  riskReasons: string[];
  lastScore: number;
}

export interface GetUnusualTimeRequest {
  userId: string;
  currentHour: number;
}

export interface GetUnusualTimeResponse {
  totalLogins: number;
  similarLogins: number;
}

export const RISK_PACKAGE_NAME = "risk";

export interface RiskProxyServiceClient {
  addFailure(request: FailureRequest, metadata?: Metadata): Observable<EventResponse>;

  logRiskEvent(request: LogRiskEventRequest, metadata?: Metadata): Observable<EventResponse>;

  updateRiskEvent(request: UpdateRiskEventRequest, metadata?: Metadata): Observable<EventResponse>;

  getUnusualTime(request: GetUnusualTimeRequest, metadata?: Metadata): Observable<GetUnusualTimeResponse>;
}

export interface RiskProxyServiceController {
  addFailure(
    request: FailureRequest,
    metadata?: Metadata,
  ): Promise<EventResponse> | Observable<EventResponse> | EventResponse;

  logRiskEvent(
    request: LogRiskEventRequest,
    metadata?: Metadata,
  ): Promise<EventResponse> | Observable<EventResponse> | EventResponse;

  updateRiskEvent(
    request: UpdateRiskEventRequest,
    metadata?: Metadata,
  ): Promise<EventResponse> | Observable<EventResponse> | EventResponse;

  getUnusualTime(
    request: GetUnusualTimeRequest,
    metadata?: Metadata,
  ): Promise<GetUnusualTimeResponse> | Observable<GetUnusualTimeResponse> | GetUnusualTimeResponse;
}

export function RiskProxyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["addFailure", "logRiskEvent", "updateRiskEvent", "getUnusualTime"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("RiskProxyService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("RiskProxyService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const RISK_PROXY_SERVICE_NAME = "RiskProxyService";
