// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: src/proto/signal.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'signal';

export enum SignalMessageType {
  TEXT = 0,
  AUDIO = 1,
  UNRECOGNIZED = -1,
}

/** Full SignalMessage serialized as JSON — preserves the complete, unmodified structure */
export interface IncomingSignalRequest {
  payload: string;
}

/** Outbound message from gate-service to be sent via Signal */
export interface OutgoingSignalRequest {
  source: string;
  message: Uint8Array;
  type: SignalMessageType;
  groupName?: string | undefined;
  groupId?: string | undefined;
}

export interface DownloadAttachmentRequest {
  attachmentId: string;
}

export interface DownloadAttachmentResponse {
  success: boolean;
  data: Uint8Array;
  error: string;
}

export interface SignalAck {
  success: boolean;
  message: string;
}

export const SIGNAL_PACKAGE_NAME = 'signal';

// ---------------------------------------------------------------------------
// IncomingSignalService — hosted by gate-service
// ---------------------------------------------------------------------------

export interface IncomingSignalServiceClient {
  receiveMessage(request: IncomingSignalRequest, metadata?: Metadata): Observable<SignalAck>;
}

export interface IncomingSignalServiceController {
  receiveMessage(
    request: IncomingSignalRequest,
    metadata?: Metadata,
  ): Promise<SignalAck> | Observable<SignalAck> | SignalAck;
}

export function IncomingSignalServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['receiveMessage'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('IncomingSignalService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('IncomingSignalService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const INCOMING_SIGNAL_SERVICE_NAME = 'IncomingSignalService';

// ---------------------------------------------------------------------------
// OutgoingSignalService — hosted by notify-service
// ---------------------------------------------------------------------------

export interface OutgoingSignalServiceClient {
  sendMessage(request: OutgoingSignalRequest, metadata?: Metadata): Observable<SignalAck>;
  downloadAttachment(request: DownloadAttachmentRequest, metadata?: Metadata): Observable<DownloadAttachmentResponse>;
}

export interface OutgoingSignalServiceController {
  sendMessage(
    request: OutgoingSignalRequest,
    metadata?: Metadata,
  ): Promise<SignalAck> | Observable<SignalAck> | SignalAck;

  downloadAttachment(
    request: DownloadAttachmentRequest,
    metadata?: Metadata,
  ): Promise<DownloadAttachmentResponse> | Observable<DownloadAttachmentResponse> | DownloadAttachmentResponse;
}

export function OutgoingSignalServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['sendMessage', 'downloadAttachment'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('OutgoingSignalService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('OutgoingSignalService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const OUTGOING_SIGNAL_SERVICE_NAME = 'OutgoingSignalService';
