// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v6.33.6
// source: src/proto/subscription.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "subscription";

export interface PlanEntry {
  id: string;
  code: string;
  name: string;
  maxTenants: number;
  maxPlatformsPerTenant: number;
  maxContactsPerTenant: number;
  maxStaffPerTenant: number;
  maxCustomCommandsPerTenant: number;
  priceCents: number;
  currency: string;
  isActive: boolean;
}

export interface GetAllPlansRequest {
}

export interface GetAllPlansResponse {
  status: boolean;
  message: string;
  plans: PlanEntry[];
}

export interface GetPlanByIdRequest {
  planId: string;
}

export interface GetPlanByIdResponse {
  status: boolean;
  message: string;
  plan: PlanEntry | undefined;
}

export interface UserSubscriptionEntry {
  id: string;
  userId: string;
  planId: string;
  status: string;
  startedAt: string;
  expiresAt: string;
  plan: PlanEntry | undefined;
}

export interface GetUserSubscriptionRequest {
  userId: string;
}

export interface GetUserSubscriptionResponse {
  status: boolean;
  message: string;
  subscription: UserSubscriptionEntry | undefined;
}

export interface SelectSubscriptionRequest {
  userId: string;
  planId: string;
  /** 'initial' | 'upgrade' | 'downgrade' | 'same' — set by BFF after comparing plans */
  kind: string;
  correlationId: string;
}

export interface SelectSubscriptionResponse {
  status: boolean;
  message: string;
  subscription: UserSubscriptionEntry | undefined;
}

export interface CancelSubscriptionRequest {
  userId: string;
  correlationId: string;
}

export interface CancelSubscriptionResponse {
  status: boolean;
  message: string;
}

export interface SubscriptionChangeEntry {
  id: string;
  userId: string;
  oldPlanId: string;
  newPlanId: string;
  kind: string;
  initiatedAt: string;
}

export interface GetSubscriptionHistoryRequest {
  userId: string;
  limit: number;
}

export interface GetSubscriptionHistoryResponse {
  status: boolean;
  message: string;
  changes: SubscriptionChangeEntry[];
}

export const SUBSCRIPTION_PACKAGE_NAME = "subscription";

export interface SubscriptionServiceClient {
  getAllPlans(request: GetAllPlansRequest, metadata?: Metadata): Observable<GetAllPlansResponse>;

  getPlanById(request: GetPlanByIdRequest, metadata?: Metadata): Observable<GetPlanByIdResponse>;

  getUserSubscription(
    request: GetUserSubscriptionRequest,
    metadata?: Metadata,
  ): Observable<GetUserSubscriptionResponse>;

  selectSubscription(request: SelectSubscriptionRequest, metadata?: Metadata): Observable<SelectSubscriptionResponse>;

  cancelSubscription(request: CancelSubscriptionRequest, metadata?: Metadata): Observable<CancelSubscriptionResponse>;

  getSubscriptionHistory(
    request: GetSubscriptionHistoryRequest,
    metadata?: Metadata,
  ): Observable<GetSubscriptionHistoryResponse>;
}

export interface SubscriptionServiceController {
  getAllPlans(
    request: GetAllPlansRequest,
    metadata?: Metadata,
  ): Promise<GetAllPlansResponse> | Observable<GetAllPlansResponse> | GetAllPlansResponse;

  getPlanById(
    request: GetPlanByIdRequest,
    metadata?: Metadata,
  ): Promise<GetPlanByIdResponse> | Observable<GetPlanByIdResponse> | GetPlanByIdResponse;

  getUserSubscription(
    request: GetUserSubscriptionRequest,
    metadata?: Metadata,
  ): Promise<GetUserSubscriptionResponse> | Observable<GetUserSubscriptionResponse> | GetUserSubscriptionResponse;

  selectSubscription(
    request: SelectSubscriptionRequest,
    metadata?: Metadata,
  ): Promise<SelectSubscriptionResponse> | Observable<SelectSubscriptionResponse> | SelectSubscriptionResponse;

  cancelSubscription(
    request: CancelSubscriptionRequest,
    metadata?: Metadata,
  ): Promise<CancelSubscriptionResponse> | Observable<CancelSubscriptionResponse> | CancelSubscriptionResponse;

  getSubscriptionHistory(
    request: GetSubscriptionHistoryRequest,
    metadata?: Metadata,
  ):
    | Promise<GetSubscriptionHistoryResponse>
    | Observable<GetSubscriptionHistoryResponse>
    | GetSubscriptionHistoryResponse;
}

export function SubscriptionServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getAllPlans",
      "getPlanById",
      "getUserSubscription",
      "selectSubscription",
      "cancelSubscription",
      "getSubscriptionHistory",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SubscriptionService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SubscriptionService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SUBSCRIPTION_SERVICE_NAME = "SubscriptionService";
