// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v4.25.9
// source: src/proto/tenant.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'tenant';

export interface GetCustomizationRequest {
  tenantId: string;
}

export interface GetCustomizationResponse {
  status: boolean;
  message: string;
  customizationJson: string;
}

export interface GetTenantRequest {
  tenantId: string;
}

export interface GetTenantResponse {
  status: boolean;
  message: string;
  id: string;
  slug: string;
  schemaName: string;
  isActive: boolean;
  billingUserId: string;
}

export interface GetPlatformCredentialsRequest {
  tenantId: string;
  platform: string;
}

export interface GetPlatformCredentialsResponse {
  status: boolean;
  message: string;
  configJson: string;
  isDefault: boolean;
}

export interface PlatformCredentialItem {
  platform: string;
  configJson: string;
  isDefault: boolean;
}

export interface GetAllPlatformCredentialsRequest {
  tenantId: string;
}

export interface GetAllPlatformCredentialsResponse {
  status: boolean;
  message: string;
  items: PlatformCredentialItem[];
}

export interface TenantPlatformEntry {
  tenantId: string;
  configJson: string;
}

export interface GetTenantsWithPlatformRequest {
  platform: string;
}

export interface GetTenantsWithPlatformResponse {
  status: boolean;
  message: string;
  entries: TenantPlatformEntry[];
}

export interface CreateTenantRequest {
  slug: string;
  billingUserId: string;
}

export interface CreateTenantResponse {
  status: boolean;
  message: string;
  id: string;
  slug: string;
  schemaName: string;
}

export interface CheckTenantSlugRequest {
  slug: string;
}

export interface CheckTenantSlugResponse {
  status: boolean;
  message: string;
  isAvailable: boolean;
}

export interface TenantEntry {
  id: string;
  slug: string;
  schemaName: string;
  isActive: boolean;
  billingUserId: string;
}

export interface GetAllTenantsRequest {}

export interface GetAllTenantsResponse {
  status: boolean;
  message: string;
  tenants: TenantEntry[];
}

export interface GetMyTenantsRequest {
  userId: string;
}

export interface GetMyTenantsResponse {
  status: boolean;
  message: string;
  tenants: TenantEntry[];
}

export interface TenantStaffEntry {
  tenantId: string;
  userId: string;
  role: string;
  tenantSlug: string;
}

export interface GetTenantsIStaffAtRequest {
  userId: string;
}

export interface GetTenantsIStaffAtResponse {
  status: boolean;
  message: string;
  memberships: TenantStaffEntry[];
}

export interface MutationResponse {
  status: boolean;
  message: string;
}

export interface TenantStaffMutationResponse {
  status: boolean;
  message: string;
  entry: TenantStaffEntry | undefined;
}

export interface AddTenantStaffRequest {
  tenantId: string;
  userId: string;
  role: string;
}

export interface RemoveTenantStaffRequest {
  tenantId: string;
  userId: string;
}

export interface ChangeTenantStaffRoleRequest {
  tenantId: string;
  userId: string;
  role: string;
}

export interface GetTenantStaffRequest {
  tenantId: string;
}

export interface GetTenantStaffResponse {
  status: boolean;
  message: string;
  members: TenantStaffEntry[];
}

export interface GetTenantStaffMembershipRequest {
  tenantId: string;
  userId: string;
}

export interface GetTenantStaffMembershipResponse {
  status: boolean;
  message: string;
  isMember: boolean;
  role: string;
}

export interface ContactEntry {
  id: string;
  email: string;
  phone: string;
  name: string;
  surname: string;
  accessLevel: string;
}

export interface ContactEntryResponse {
  status: boolean;
  message: string;
  contact: ContactEntry | undefined;
}

export interface AddContactRequest {
  tenantId: string;
  email: string;
  phone: string;
  name: string;
  surname: string;
  accessLevel: string;
}

export interface UpdateContactRequest {
  contactId: string;
  email: string;
  phone: string;
  name: string;
  surname: string;
}

export interface GetTenantContactsRequest {
  tenantId: string;
}

export interface GetTenantContactsResponse {
  status: boolean;
  message: string;
  contacts: ContactEntry[];
}

export interface RemoveContactFromTenantRequest {
  tenantId: string;
  contactId: string;
}

export interface UpdateCustomizationRequest {
  tenantId: string;
  customizationJson: string;
}

export interface UpdateCustomizationResponse {
  status: boolean;
  message: string;
}

export interface UpsertPlatformCredentialsRequest {
  tenantId: string;
  platform: string;
  configJson: string;
}

export interface UpsertPlatformCredentialsResponse {
  status: boolean;
  message: string;
}

export interface TenantCommandConfigEntry {
  id: string;
  commandName: string;
  active: boolean;
  parametersOverrideJson: string;
  userTypes: string[];
  actionsJson: string;
  descriptionI18nJson: string;
}

export interface GetTenantCommandConfigsRequest {
  tenantId: string;
}

export interface GetTenantCommandConfigsResponse {
  status: boolean;
  message: string;
  configs: TenantCommandConfigEntry[];
}

export interface UpsertTenantCommandConfigRequest {
  tenantId: string;
  commandName: string;
  active: boolean;
  parametersOverrideJson: string;
  userTypes: string[];
  actionsJson: string;
  descriptionI18nJson: string;
}

export interface UpsertTenantCommandConfigResponse {
  status: boolean;
  message: string;
}

export interface DeleteTenantCommandConfigRequest {
  tenantId: string;
  commandName: string;
}

export interface DeleteTenantCommandConfigResponse {
  status: boolean;
  message: string;
}

export interface GetPromptForContextRequest {
  tenantId: string;
  commandId: string;
  userType: string;
}

export interface GetPromptForContextResponse {
  status: boolean;
  message: string;
  prompt: string;
}

export interface TenantPromptOverrideEntry {
  id: string;
  tenantId: string;
  commandId: string;
  userType: string;
  descriptionI18nJson: string;
  prompt: string;
}

export interface UpsertTenantPromptOverrideRequest {
  tenantId: string;
  commandId: string;
  userType: string;
  descriptionI18nJson: string;
  prompt: string;
}

export interface UpsertTenantPromptOverrideResponse {
  status: boolean;
  message: string;
}

export interface GetTenantPromptOverridesRequest {
  tenantId: string;
}

export interface GetTenantPromptOverridesResponse {
  status: boolean;
  message: string;
  overrides: TenantPromptOverrideEntry[];
}

export interface TenantUsageEntry {
  tenantId: string;
  staff: number;
  platforms: number;
  contacts: number;
  customCommands: number;
}

export interface GetTenantUsageRequest {
  billingUserId: string;
}

export interface GetTenantUsageResponse {
  status: boolean;
  message: string;
  tenants: number;
  perTenant: TenantUsageEntry[];
}

export interface TransferTenantBillingRequest {
  tenantId: string;
  newBillingUserId: string;
}

export interface SetTenantActiveRequest {
  tenantId: string;
  active: boolean;
}

export interface DeleteTenantRequest {
  tenantId: string;
  slugConfirmation: string;
}

export interface RecordAuditEntryRequest {
  tenantId: string;
  userId: string;
  action: string;
  payloadJson: string;
  ip: string;
  userAgent: string;
  correlationId: string;
}

export interface AuditEntry {
  id: string;
  tenantId: string;
  userId: string;
  action: string;
  payloadJson: string;
  correlationId: string;
  createdAt: string;
}

export interface GetTenantAuditLogRequest {
  tenantId: string;
  limit: number;
}

export interface GetTenantAuditLogResponse {
  status: boolean;
  message: string;
  entries: AuditEntry[];
}

export const TENANT_PACKAGE_NAME = 'tenant';

export interface TenantServiceClient {
  getCustomization(request: GetCustomizationRequest, metadata?: Metadata): Observable<GetCustomizationResponse>;

  getTenant(request: GetTenantRequest, metadata?: Metadata): Observable<GetTenantResponse>;

  getPlatformCredentials(
    request: GetPlatformCredentialsRequest,
    metadata?: Metadata,
  ): Observable<GetPlatformCredentialsResponse>;

  getTenantsWithPlatform(
    request: GetTenantsWithPlatformRequest,
    metadata?: Metadata,
  ): Observable<GetTenantsWithPlatformResponse>;

  getAllPlatformCredentials(
    request: GetAllPlatformCredentialsRequest,
    metadata?: Metadata,
  ): Observable<GetAllPlatformCredentialsResponse>;

  createTenant(request: CreateTenantRequest, metadata?: Metadata): Observable<CreateTenantResponse>;

  checkTenantSlug(request: CheckTenantSlugRequest, metadata?: Metadata): Observable<CheckTenantSlugResponse>;

  getAllTenants(request: GetAllTenantsRequest, metadata?: Metadata): Observable<GetAllTenantsResponse>;

  getMyTenants(request: GetMyTenantsRequest, metadata?: Metadata): Observable<GetMyTenantsResponse>;

  getTenantsIStaffAt(request: GetTenantsIStaffAtRequest, metadata?: Metadata): Observable<GetTenantsIStaffAtResponse>;

  updateCustomization(
    request: UpdateCustomizationRequest,
    metadata?: Metadata,
  ): Observable<UpdateCustomizationResponse>;

  upsertPlatformCredentials(
    request: UpsertPlatformCredentialsRequest,
    metadata?: Metadata,
  ): Observable<UpsertPlatformCredentialsResponse>;

  getTenantCommandConfigs(
    request: GetTenantCommandConfigsRequest,
    metadata?: Metadata,
  ): Observable<GetTenantCommandConfigsResponse>;

  upsertTenantCommandConfig(
    request: UpsertTenantCommandConfigRequest,
    metadata?: Metadata,
  ): Observable<UpsertTenantCommandConfigResponse>;

  deleteTenantCommandConfig(
    request: DeleteTenantCommandConfigRequest,
    metadata?: Metadata,
  ): Observable<DeleteTenantCommandConfigResponse>;

  getPromptForContext(
    request: GetPromptForContextRequest,
    metadata?: Metadata,
  ): Observable<GetPromptForContextResponse>;

  upsertTenantPromptOverride(
    request: UpsertTenantPromptOverrideRequest,
    metadata?: Metadata,
  ): Observable<UpsertTenantPromptOverrideResponse>;

  getTenantPromptOverrides(
    request: GetTenantPromptOverridesRequest,
    metadata?: Metadata,
  ): Observable<GetTenantPromptOverridesResponse>;

  addTenantStaff(request: AddTenantStaffRequest, metadata?: Metadata): Observable<TenantStaffMutationResponse>;

  removeTenantStaff(request: RemoveTenantStaffRequest, metadata?: Metadata): Observable<TenantStaffMutationResponse>;

  changeTenantStaffRole(
    request: ChangeTenantStaffRoleRequest,
    metadata?: Metadata,
  ): Observable<TenantStaffMutationResponse>;

  getTenantStaff(request: GetTenantStaffRequest, metadata?: Metadata): Observable<GetTenantStaffResponse>;

  getTenantStaffMembership(
    request: GetTenantStaffMembershipRequest,
    metadata?: Metadata,
  ): Observable<GetTenantStaffMembershipResponse>;

  addContact(request: AddContactRequest, metadata?: Metadata): Observable<ContactEntryResponse>;

  updateContact(request: UpdateContactRequest, metadata?: Metadata): Observable<ContactEntryResponse>;

  getTenantContacts(request: GetTenantContactsRequest, metadata?: Metadata): Observable<GetTenantContactsResponse>;

  removeContactFromTenant(request: RemoveContactFromTenantRequest, metadata?: Metadata): Observable<MutationResponse>;

  getTenantUsage(request: GetTenantUsageRequest, metadata?: Metadata): Observable<GetTenantUsageResponse>;

  transferTenantBilling(request: TransferTenantBillingRequest, metadata?: Metadata): Observable<MutationResponse>;

  setTenantActive(request: SetTenantActiveRequest, metadata?: Metadata): Observable<MutationResponse>;

  deleteTenant(request: DeleteTenantRequest, metadata?: Metadata): Observable<MutationResponse>;

  recordAuditEntry(request: RecordAuditEntryRequest, metadata?: Metadata): Observable<MutationResponse>;

  getTenantAuditLog(request: GetTenantAuditLogRequest, metadata?: Metadata): Observable<GetTenantAuditLogResponse>;
}

export interface TenantServiceController {
  getCustomization(
    request: GetCustomizationRequest,
    metadata?: Metadata,
  ): Promise<GetCustomizationResponse> | Observable<GetCustomizationResponse> | GetCustomizationResponse;

  getTenant(
    request: GetTenantRequest,
    metadata?: Metadata,
  ): Promise<GetTenantResponse> | Observable<GetTenantResponse> | GetTenantResponse;

  getPlatformCredentials(
    request: GetPlatformCredentialsRequest,
    metadata?: Metadata,
  ):
    | Promise<GetPlatformCredentialsResponse>
    | Observable<GetPlatformCredentialsResponse>
    | GetPlatformCredentialsResponse;

  getTenantsWithPlatform(
    request: GetTenantsWithPlatformRequest,
    metadata?: Metadata,
  ):
    | Promise<GetTenantsWithPlatformResponse>
    | Observable<GetTenantsWithPlatformResponse>
    | GetTenantsWithPlatformResponse;

  getAllPlatformCredentials(
    request: GetAllPlatformCredentialsRequest,
    metadata?: Metadata,
  ):
    | Promise<GetAllPlatformCredentialsResponse>
    | Observable<GetAllPlatformCredentialsResponse>
    | GetAllPlatformCredentialsResponse;

  createTenant(
    request: CreateTenantRequest,
    metadata?: Metadata,
  ): Promise<CreateTenantResponse> | Observable<CreateTenantResponse> | CreateTenantResponse;

  checkTenantSlug(
    request: CheckTenantSlugRequest,
    metadata?: Metadata,
  ): Promise<CheckTenantSlugResponse> | Observable<CheckTenantSlugResponse> | CheckTenantSlugResponse;

  getAllTenants(
    request: GetAllTenantsRequest,
    metadata?: Metadata,
  ): Promise<GetAllTenantsResponse> | Observable<GetAllTenantsResponse> | GetAllTenantsResponse;

  getMyTenants(
    request: GetMyTenantsRequest,
    metadata?: Metadata,
  ): Promise<GetMyTenantsResponse> | Observable<GetMyTenantsResponse> | GetMyTenantsResponse;

  getTenantsIStaffAt(
    request: GetTenantsIStaffAtRequest,
    metadata?: Metadata,
  ): Promise<GetTenantsIStaffAtResponse> | Observable<GetTenantsIStaffAtResponse> | GetTenantsIStaffAtResponse;

  updateCustomization(
    request: UpdateCustomizationRequest,
    metadata?: Metadata,
  ): Promise<UpdateCustomizationResponse> | Observable<UpdateCustomizationResponse> | UpdateCustomizationResponse;

  upsertPlatformCredentials(
    request: UpsertPlatformCredentialsRequest,
    metadata?: Metadata,
  ):
    | Promise<UpsertPlatformCredentialsResponse>
    | Observable<UpsertPlatformCredentialsResponse>
    | UpsertPlatformCredentialsResponse;

  getTenantCommandConfigs(
    request: GetTenantCommandConfigsRequest,
    metadata?: Metadata,
  ):
    | Promise<GetTenantCommandConfigsResponse>
    | Observable<GetTenantCommandConfigsResponse>
    | GetTenantCommandConfigsResponse;

  upsertTenantCommandConfig(
    request: UpsertTenantCommandConfigRequest,
    metadata?: Metadata,
  ):
    | Promise<UpsertTenantCommandConfigResponse>
    | Observable<UpsertTenantCommandConfigResponse>
    | UpsertTenantCommandConfigResponse;

  deleteTenantCommandConfig(
    request: DeleteTenantCommandConfigRequest,
    metadata?: Metadata,
  ):
    | Promise<DeleteTenantCommandConfigResponse>
    | Observable<DeleteTenantCommandConfigResponse>
    | DeleteTenantCommandConfigResponse;

  getPromptForContext(
    request: GetPromptForContextRequest,
    metadata?: Metadata,
  ): Promise<GetPromptForContextResponse> | Observable<GetPromptForContextResponse> | GetPromptForContextResponse;

  upsertTenantPromptOverride(
    request: UpsertTenantPromptOverrideRequest,
    metadata?: Metadata,
  ):
    | Promise<UpsertTenantPromptOverrideResponse>
    | Observable<UpsertTenantPromptOverrideResponse>
    | UpsertTenantPromptOverrideResponse;

  getTenantPromptOverrides(
    request: GetTenantPromptOverridesRequest,
    metadata?: Metadata,
  ):
    | Promise<GetTenantPromptOverridesResponse>
    | Observable<GetTenantPromptOverridesResponse>
    | GetTenantPromptOverridesResponse;

  addTenantStaff(
    request: AddTenantStaffRequest,
    metadata?: Metadata,
  ): Promise<TenantStaffMutationResponse> | Observable<TenantStaffMutationResponse> | TenantStaffMutationResponse;

  removeTenantStaff(
    request: RemoveTenantStaffRequest,
    metadata?: Metadata,
  ): Promise<TenantStaffMutationResponse> | Observable<TenantStaffMutationResponse> | TenantStaffMutationResponse;

  changeTenantStaffRole(
    request: ChangeTenantStaffRoleRequest,
    metadata?: Metadata,
  ): Promise<TenantStaffMutationResponse> | Observable<TenantStaffMutationResponse> | TenantStaffMutationResponse;

  getTenantStaff(
    request: GetTenantStaffRequest,
    metadata?: Metadata,
  ): Promise<GetTenantStaffResponse> | Observable<GetTenantStaffResponse> | GetTenantStaffResponse;

  getTenantStaffMembership(
    request: GetTenantStaffMembershipRequest,
    metadata?: Metadata,
  ):
    | Promise<GetTenantStaffMembershipResponse>
    | Observable<GetTenantStaffMembershipResponse>
    | GetTenantStaffMembershipResponse;

  addContact(
    request: AddContactRequest,
    metadata?: Metadata,
  ): Promise<ContactEntryResponse> | Observable<ContactEntryResponse> | ContactEntryResponse;

  updateContact(
    request: UpdateContactRequest,
    metadata?: Metadata,
  ): Promise<ContactEntryResponse> | Observable<ContactEntryResponse> | ContactEntryResponse;

  getTenantContacts(
    request: GetTenantContactsRequest,
    metadata?: Metadata,
  ): Promise<GetTenantContactsResponse> | Observable<GetTenantContactsResponse> | GetTenantContactsResponse;

  removeContactFromTenant(
    request: RemoveContactFromTenantRequest,
    metadata?: Metadata,
  ): Promise<MutationResponse> | Observable<MutationResponse> | MutationResponse;

  getTenantUsage(
    request: GetTenantUsageRequest,
    metadata?: Metadata,
  ): Promise<GetTenantUsageResponse> | Observable<GetTenantUsageResponse> | GetTenantUsageResponse;

  transferTenantBilling(
    request: TransferTenantBillingRequest,
    metadata?: Metadata,
  ): Promise<MutationResponse> | Observable<MutationResponse> | MutationResponse;

  setTenantActive(
    request: SetTenantActiveRequest,
    metadata?: Metadata,
  ): Promise<MutationResponse> | Observable<MutationResponse> | MutationResponse;

  deleteTenant(
    request: DeleteTenantRequest,
    metadata?: Metadata,
  ): Promise<MutationResponse> | Observable<MutationResponse> | MutationResponse;

  recordAuditEntry(
    request: RecordAuditEntryRequest,
    metadata?: Metadata,
  ): Promise<MutationResponse> | Observable<MutationResponse> | MutationResponse;

  getTenantAuditLog(
    request: GetTenantAuditLogRequest,
    metadata?: Metadata,
  ): Promise<GetTenantAuditLogResponse> | Observable<GetTenantAuditLogResponse> | GetTenantAuditLogResponse;
}

export function TenantServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getCustomization',
      'getTenant',
      'getPlatformCredentials',
      'getTenantsWithPlatform',
      'getAllPlatformCredentials',
      'createTenant',
      'checkTenantSlug',
      'getAllTenants',
      'getMyTenants',
      'getTenantsIStaffAt',
      'updateCustomization',
      'upsertPlatformCredentials',
      'getTenantCommandConfigs',
      'upsertTenantCommandConfig',
      'deleteTenantCommandConfig',
      'getPromptForContext',
      'upsertTenantPromptOverride',
      'getTenantPromptOverrides',
      'addTenantStaff',
      'removeTenantStaff',
      'changeTenantStaffRole',
      'getTenantStaff',
      'getTenantStaffMembership',
      'addContact',
      'updateContact',
      'getTenantContacts',
      'removeContactFromTenant',
      'getTenantUsage',
      'transferTenantBilling',
      'setTenantActive',
      'deleteTenant',
      'recordAuditEntry',
      'getTenantAuditLog',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('TenantService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('TenantService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TENANT_SERVICE_NAME = 'TenantService';
