// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/tenant.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'tenant';

export interface GetCustomizationRequest {
  tenantId: string;
}

export interface GetCustomizationResponse {
  status: boolean;
  message: string;
  customizationJson: string;
}

export interface GetTenantRequest {
  tenantId: string;
}

export interface GetTenantResponse {
  status: boolean;
  message: string;
  id: string;
  slug: string;
  schemaName: string;
  isActive: boolean;
}

export interface GetPlatformCredentialsRequest {
  tenantId: string;
  platform: string;
}

export interface GetPlatformCredentialsResponse {
  status: boolean;
  message: string;
  configJson: string;
}

export interface TenantPlatformEntry {
  tenantId: string;
  configJson: string;
}

export interface GetTenantsWithPlatformRequest {
  platform: string;
}

export interface GetTenantsWithPlatformResponse {
  status: boolean;
  message: string;
  entries: TenantPlatformEntry[];
}

export const TENANT_PACKAGE_NAME = 'tenant';

export interface TenantServiceClient {
  getCustomization(request: GetCustomizationRequest, metadata?: Metadata): Observable<GetCustomizationResponse>;
  getTenant(request: GetTenantRequest, metadata?: Metadata): Observable<GetTenantResponse>;
  getPlatformCredentials(request: GetPlatformCredentialsRequest, metadata?: Metadata): Observable<GetPlatformCredentialsResponse>;
  getTenantsWithPlatform(request: GetTenantsWithPlatformRequest, metadata?: Metadata): Observable<GetTenantsWithPlatformResponse>;
}

export interface TenantServiceController {
  getCustomization(
    request: GetCustomizationRequest,
    metadata?: Metadata,
  ): Promise<GetCustomizationResponse> | Observable<GetCustomizationResponse> | GetCustomizationResponse;

  getTenant(
    request: GetTenantRequest,
    metadata?: Metadata,
  ): Promise<GetTenantResponse> | Observable<GetTenantResponse> | GetTenantResponse;

  getPlatformCredentials(
    request: GetPlatformCredentialsRequest,
    metadata?: Metadata,
  ): Promise<GetPlatformCredentialsResponse> | Observable<GetPlatformCredentialsResponse> | GetPlatformCredentialsResponse;

  getTenantsWithPlatform(
    request: GetTenantsWithPlatformRequest,
    metadata?: Metadata,
  ): Promise<GetTenantsWithPlatformResponse> | Observable<GetTenantsWithPlatformResponse> | GetTenantsWithPlatformResponse;
}

export function TenantServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['getCustomization', 'getTenant', 'getPlatformCredentials', 'getTenantsWithPlatform'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('TenantService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('TenantService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TENANT_SERVICE_NAME = 'TenantService';
