// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/tenant.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'tenant';

export interface GetCustomizationRequest {
  tenantId: string;
}

export interface GetCustomizationResponse {
  status: boolean;
  message: string;
  customizationJson: string;
}

export interface GetTenantRequest {
  tenantId: string;
}

export interface GetTenantResponse {
  status: boolean;
  message: string;
  id: string;
  slug: string;
  schemaName: string;
  isActive: boolean;
}

export interface GetPlatformCredentialsRequest {
  tenantId: string;
  platform: string;
}

export interface GetPlatformCredentialsResponse {
  status: boolean;
  message: string;
  configJson: string;
}

export interface TenantPlatformEntry {
  tenantId: string;
  configJson: string;
}

export interface GetTenantsWithPlatformRequest {
  platform: string;
}

export interface GetTenantsWithPlatformResponse {
  status: boolean;
  message: string;
  entries: TenantPlatformEntry[];
}

export interface CreateTenantRequest {
  slug: string;
}

export interface CreateTenantResponse {
  status: boolean;
  message: string;
  id: string;
  slug: string;
  schemaName: string;
}

export interface TenantEntry {
  id: string;
  slug: string;
  schemaName: string;
  isActive: boolean;
}

export interface GetAllTenantsRequest {}

export interface GetAllTenantsResponse {
  status: boolean;
  message: string;
  tenants: TenantEntry[];
}

export interface UpdateCustomizationRequest {
  tenantId: string;
  customizationJson: string;
}

export interface UpdateCustomizationResponse {
  status: boolean;
  message: string;
}

export interface UpsertPlatformCredentialsRequest {
  tenantId: string;
  platform: string;
  configJson: string;
}

export interface UpsertPlatformCredentialsResponse {
  status: boolean;
  message: string;
}

export interface TenantCommandConfigEntry {
  id: string;
  commandId: string;
  commandName: string;
  active: boolean;
  parametersOverrideJson: string;
}

export interface GetTenantCommandConfigsRequest {
  tenantId: string;
}

export interface GetTenantCommandConfigsResponse {
  status: boolean;
  message: string;
  configs: TenantCommandConfigEntry[];
}

export interface UpsertTenantCommandConfigRequest {
  tenantId: string;
  commandId: string;
  active: boolean;
  parametersOverrideJson: string;
}

export interface UpsertTenantCommandConfigResponse {
  status: boolean;
  message: string;
}

export interface GetPromptForContextRequest {
  tenantId: string;
  commandId: string;
  userType: string;
}

export interface GetPromptForContextResponse {
  status: boolean;
  message: string;
  prompt: string;
}

export interface TenantPromptOverrideEntry {
  id: string;
  tenantId: string;
  commandId: string;
  userType: string;
  description: string;
  prompt: string;
}

export interface UpsertTenantPromptOverrideRequest {
  tenantId: string;
  commandId: string;
  userType: string;
  description: string;
  prompt: string;
}

export interface UpsertTenantPromptOverrideResponse {
  status: boolean;
  message: string;
}

export interface GetTenantPromptOverridesRequest {
  tenantId: string;
}

export interface GetTenantPromptOverridesResponse {
  status: boolean;
  message: string;
  overrides: TenantPromptOverrideEntry[];
}

export const TENANT_PACKAGE_NAME = 'tenant';

export interface TenantServiceClient {
  getCustomization(request: GetCustomizationRequest, metadata?: Metadata): Observable<GetCustomizationResponse>;
  getTenant(request: GetTenantRequest, metadata?: Metadata): Observable<GetTenantResponse>;
  getPlatformCredentials(request: GetPlatformCredentialsRequest, metadata?: Metadata): Observable<GetPlatformCredentialsResponse>;
  getTenantsWithPlatform(request: GetTenantsWithPlatformRequest, metadata?: Metadata): Observable<GetTenantsWithPlatformResponse>;
  createTenant(request: CreateTenantRequest, metadata?: Metadata): Observable<CreateTenantResponse>;
  getAllTenants(request: GetAllTenantsRequest, metadata?: Metadata): Observable<GetAllTenantsResponse>;
  updateCustomization(request: UpdateCustomizationRequest, metadata?: Metadata): Observable<UpdateCustomizationResponse>;
  upsertPlatformCredentials(request: UpsertPlatformCredentialsRequest, metadata?: Metadata): Observable<UpsertPlatformCredentialsResponse>;
  getTenantCommandConfigs(request: GetTenantCommandConfigsRequest, metadata?: Metadata): Observable<GetTenantCommandConfigsResponse>;
  upsertTenantCommandConfig(request: UpsertTenantCommandConfigRequest, metadata?: Metadata): Observable<UpsertTenantCommandConfigResponse>;
  getPromptForContext(request: GetPromptForContextRequest, metadata?: Metadata): Observable<GetPromptForContextResponse>;
  upsertTenantPromptOverride(request: UpsertTenantPromptOverrideRequest, metadata?: Metadata): Observable<UpsertTenantPromptOverrideResponse>;
  getTenantPromptOverrides(request: GetTenantPromptOverridesRequest, metadata?: Metadata): Observable<GetTenantPromptOverridesResponse>;
}

export interface TenantServiceController {
  getCustomization(
    request: GetCustomizationRequest,
    metadata?: Metadata,
  ): Promise<GetCustomizationResponse> | Observable<GetCustomizationResponse> | GetCustomizationResponse;

  getTenant(
    request: GetTenantRequest,
    metadata?: Metadata,
  ): Promise<GetTenantResponse> | Observable<GetTenantResponse> | GetTenantResponse;

  getPlatformCredentials(
    request: GetPlatformCredentialsRequest,
    metadata?: Metadata,
  ): Promise<GetPlatformCredentialsResponse> | Observable<GetPlatformCredentialsResponse> | GetPlatformCredentialsResponse;

  getTenantsWithPlatform(
    request: GetTenantsWithPlatformRequest,
    metadata?: Metadata,
  ): Promise<GetTenantsWithPlatformResponse> | Observable<GetTenantsWithPlatformResponse> | GetTenantsWithPlatformResponse;

  createTenant(
    request: CreateTenantRequest,
    metadata?: Metadata,
  ): Promise<CreateTenantResponse> | Observable<CreateTenantResponse> | CreateTenantResponse;

  getAllTenants(
    request: GetAllTenantsRequest,
    metadata?: Metadata,
  ): Promise<GetAllTenantsResponse> | Observable<GetAllTenantsResponse> | GetAllTenantsResponse;

  updateCustomization(
    request: UpdateCustomizationRequest,
    metadata?: Metadata,
  ): Promise<UpdateCustomizationResponse> | Observable<UpdateCustomizationResponse> | UpdateCustomizationResponse;

  upsertPlatformCredentials(
    request: UpsertPlatformCredentialsRequest,
    metadata?: Metadata,
  ): Promise<UpsertPlatformCredentialsResponse> | Observable<UpsertPlatformCredentialsResponse> | UpsertPlatformCredentialsResponse;

  getTenantCommandConfigs(
    request: GetTenantCommandConfigsRequest,
    metadata?: Metadata,
  ): Promise<GetTenantCommandConfigsResponse> | Observable<GetTenantCommandConfigsResponse> | GetTenantCommandConfigsResponse;

  upsertTenantCommandConfig(
    request: UpsertTenantCommandConfigRequest,
    metadata?: Metadata,
  ): Promise<UpsertTenantCommandConfigResponse> | Observable<UpsertTenantCommandConfigResponse> | UpsertTenantCommandConfigResponse;

  getPromptForContext(
    request: GetPromptForContextRequest,
    metadata?: Metadata,
  ): Promise<GetPromptForContextResponse> | Observable<GetPromptForContextResponse> | GetPromptForContextResponse;

  upsertTenantPromptOverride(
    request: UpsertTenantPromptOverrideRequest,
    metadata?: Metadata,
  ): Promise<UpsertTenantPromptOverrideResponse> | Observable<UpsertTenantPromptOverrideResponse> | UpsertTenantPromptOverrideResponse;

  getTenantPromptOverrides(
    request: GetTenantPromptOverridesRequest,
    metadata?: Metadata,
  ): Promise<GetTenantPromptOverridesResponse> | Observable<GetTenantPromptOverridesResponse> | GetTenantPromptOverridesResponse;
}

export function TenantServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getCustomization',
      'getTenant',
      'getPlatformCredentials',
      'getTenantsWithPlatform',
      'createTenant',
      'getAllTenants',
      'updateCustomization',
      'upsertPlatformCredentials',
      'getTenantCommandConfigs',
      'upsertTenantCommandConfig',
      'getPromptForContext',
      'upsertTenantPromptOverride',
      'getTenantPromptOverrides',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('TenantService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('TenantService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TENANT_SERVICE_NAME = 'TenantService';
