// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/user.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export enum Status {
  PENDING = 0,
  ACTIVE = 1,
  SUSPENDED = 2,
  BANNED = 3,
  UNRECOGNIZED = -1,
}

export enum UserType {
  OWNER = 0,
  ADMIN = 1,
  SUPER_USER = 2,
  MEMBER = 3,
  USER = 4,
  UNRECOGNIZED = -1,
}

export interface CheckExistRequest {
  email: string;
}

export interface CheckExistResponse {
  exist: boolean;
}

export interface GetUserByEmailRequest {
  email: string;
}

export interface AddUserRequest {
  email: string;
  phone: string;
  name: string;
  surname: string;
  ownerId?: string | undefined;
  type?: UserType | undefined;
  password?: string | undefined;
}

export interface GetUserRequest {
  id: string;
}

export interface GetUserByPhoneRequest {
  phone: string;
}

export interface UpdateUserRequest {
  id: string;
  email?: string | undefined;
  phone?: string | undefined;
  name?: string | undefined;
  surname?: string | undefined;
  status?: Status | undefined;
  type?: UserType | undefined;
}

export interface UpdateUserStatusRequest {
  id: string;
  status: Status;
}

export interface UpdateUserRoleRequest {
  id: string;
  type: UserType;
}

export interface RemoveUserRequest {
  id: string;
}

export interface GetAllUsersRequest {
  page: number;
  limit: number;
}

export interface UserResponse {
  status: boolean;
  message: string;
  data?: UserData | undefined;
}

export interface GetAllUsersResponse {
  status: boolean;
  message: string;
  data: UserData[];
  total: number;
}

export interface UserData {
  id: string;
  email: string;
  phone: string;
  name: string;
  surname: string;
  status: Status;
  type: UserType;
}

export const USER_PACKAGE_NAME = "user";

export interface UserProxyServiceClient {
  addUser(request: AddUserRequest, metadata?: Metadata): Observable<UserResponse>;

  getUser(request: GetUserRequest, metadata?: Metadata): Observable<UserResponse>;

  getUserByEmail(request: GetUserByEmailRequest, metadata?: Metadata): Observable<UserResponse>;

  getUserByPhone(request: GetUserByPhoneRequest, metadata?: Metadata): Observable<UserResponse>;

  updateUser(request: UpdateUserRequest, metadata?: Metadata): Observable<UserResponse>;

  updateUserStatus(request: UpdateUserStatusRequest, metadata?: Metadata): Observable<UserResponse>;

  updateUserRole(request: UpdateUserRoleRequest, metadata?: Metadata): Observable<UserResponse>;

  removeUser(request: RemoveUserRequest, metadata?: Metadata): Observable<UserResponse>;

  getAllUsers(request: GetAllUsersRequest, metadata?: Metadata): Observable<GetAllUsersResponse>;

  checkExist(request: CheckExistRequest, metadata?: Metadata): Observable<CheckExistResponse>;
}

export interface UserProxyServiceController {
  addUser(
    request: AddUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getUser(
    request: GetUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getUserByEmail(
    request: GetUserByEmailRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getUserByPhone(
    request: GetUserByPhoneRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  updateUser(
    request: UpdateUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  updateUserStatus(
    request: UpdateUserStatusRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  updateUserRole(
    request: UpdateUserRoleRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  removeUser(
    request: RemoveUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getAllUsers(
    request: GetAllUsersRequest,
    metadata?: Metadata,
  ): Promise<GetAllUsersResponse> | Observable<GetAllUsersResponse> | GetAllUsersResponse;

  checkExist(
    request: CheckExistRequest,
    metadata?: Metadata,
  ): Promise<CheckExistResponse> | Observable<CheckExistResponse> | CheckExistResponse;
}

export function UserProxyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "addUser",
      "getUser",
      "getUserByEmail",
      "getUserByPhone",
      "updateUser",
      "updateUserStatus",
      "updateUserRole",
      "removeUser",
      "getAllUsers",
      "checkExist",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserProxyService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserProxyService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_PROXY_SERVICE_NAME = "UserProxyService";
