// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: src/proto/user.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'user';

export enum UserType {
  ADMIN = 0,
  SUPER_USER = 1,
  MEMBER = 2,
  USER = 3,
  UNRECOGNIZED = -1,
}

export interface AddUserRequest {
  email: string;
  phone: string;
  name: string;
  surname: string;
  type: UserType;
}

export interface GetUserRequest {
  id: string;
}

export interface GetUserByPhoneRequest {
  phone: string;
}

export interface UpdateUserRequest {
  id: string;
  email?: string | undefined;
  phone?: string | undefined;
  name?: string | undefined;
  surname?: string | undefined;
  type?: UserType | undefined;
}

export interface RemoveUserRequest {
  id: string;
}

export interface GetAllUsersRequest {
  page: number;
  limit: number;
}

export interface UserResponse {
  status: boolean;
  message: string;
  data?: UserData | undefined;
}

export interface GetAllUsersResponse {
  status: boolean;
  message: string;
  data: UserData[];
  total: number;
}

export interface UserData {
  id: string;
  email: string;
  phone: string;
  name: string;
  surname: string;
  suspended: boolean;
  type: UserType;
}

export const USER_PACKAGE_NAME = 'user';

export interface UserProxyServiceClient {
  addUser(request: AddUserRequest, metadata?: Metadata): Observable<UserResponse>;

  getUser(request: GetUserRequest, metadata?: Metadata): Observable<UserResponse>;

  getUserByPhone(request: GetUserByPhoneRequest, metadata?: Metadata): Observable<UserResponse>;

  updateUser(request: UpdateUserRequest, metadata?: Metadata): Observable<UserResponse>;

  removeUser(request: RemoveUserRequest, metadata?: Metadata): Observable<UserResponse>;

  getAllUsers(request: GetAllUsersRequest, metadata?: Metadata): Observable<GetAllUsersResponse>;
}

export interface UserProxyServiceController {
  addUser(
    request: AddUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getUser(
    request: GetUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getUserByPhone(
    request: GetUserByPhoneRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  updateUser(
    request: UpdateUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  removeUser(
    request: RemoveUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getAllUsers(
    request: GetAllUsersRequest,
    metadata?: Metadata,
  ): Promise<GetAllUsersResponse> | Observable<GetAllUsersResponse> | GetAllUsersResponse;
}

export function UserProxyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['addUser', 'getUser', 'getUserByPhone', 'updateUser', 'removeUser', 'getAllUsers'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('UserProxyService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('UserProxyService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_PROXY_SERVICE_NAME = 'UserProxyService';
