// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v4.25.9
// source: src/proto/user.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'user';

/** User account status */
export enum Status {
  /** PENDING - Newly created, awaiting verification */
  PENDING = 0,
  /** ACTIVE - Active and verified */
  ACTIVE = 1,
  /** SUSPENDED - Temporarily disabled */
  SUSPENDED = 2,
  /** BANNED - Permanently banned */
  BANNED = 3,
  UNRECOGNIZED = -1,
}

/** User permission level/role */
export enum UserType {
  /** OWNER - System owner - full access */
  OWNER = 0,
  /** ADMIN - Administrator - can manage users and settings */
  ADMIN = 1,
  /** SUPER_USER - Power user - can create resources */
  SUPER_USER = 2,
  /** MEMBER - Team member - standard access */
  MEMBER = 3,
  /** USER - Basic user - limited access */
  USER = 4,
  UNRECOGNIZED = -1,
}

/** Check if user exists by email */
export interface CheckExistRequest {
  /** Email to check existence */
  email: string;
}

export interface CheckExistResponse {
  /** True if user exists */
  exist: boolean;
}

/** Get user by email address */
export interface GetUserByEmailRequest {
  /** User email address */
  email: string;
}

/** Create new user */
export interface AddUserRequest {
  /** User email (unique) */
  email: string;
  /** Phone number */
  phone: string;
  /** First name */
  name: string;
  /** Last name */
  surname: string;
  /** Account status (default: PENDING) */
  status?: Status | undefined;
  /** Phone owner information */
  phoneOwner?: string | undefined;
  /** User role (default: USER) */
  type?: UserType | undefined;
  /** Initial password (if provided) */
  password?: string | undefined;
}

/** Retrieve user by ID */
export interface GetUserRequest {
  /** User ID (UUID) */
  id: string;
}

/** Get user by phone number */
export interface GetUserByPhoneRequest {
  /** Phone number */
  phone: string;
}

/** Update user information */
export interface UpdateUserRequest {
  /** User ID to update */
  id: string;
  /** New email */
  email?: string | undefined;
  /** New phone */
  phone?: string | undefined;
  /** New first name */
  name?: string | undefined;
  /** New last name */
  surname?: string | undefined;
  /** New status */
  status?: Status | undefined;
  /** New role */
  type?: UserType | undefined;
}

/** Update only user status */
export interface UpdateUserStatusRequest {
  /** User ID */
  id: string;
  /** New status */
  status: Status;
}

/** Update only user role/type */
export interface UpdateUserRoleRequest {
  /** User ID */
  id: string;
  /** New role */
  type: UserType;
}

/** Delete user by ID (soft delete) */
export interface RemoveUserRequest {
  /** User ID to delete */
  id: string;
}

/** Pagination parameters for user list */
export interface GetAllUsersRequest {
  /** Page number (0-indexed) */
  page: number;
  /** Items per page */
  limit: number;
}

/** Generic user operation response */
export interface UserResponse {
  /** Operation success flag */
  status: boolean;
  /** Response message */
  message: string;
  /** Response data (if applicable) */
  data?: UserData | undefined;
}

/** Paginated user list response */
export interface GetAllUsersResponse {
  /** Operation success flag */
  status: boolean;
  /** Response message */
  message: string;
  /** List of users */
  data: UserData[];
  /** Total count of users matching query */
  total: number;
}

/** User data object */
export interface UserData {
  /** User ID (UUID) */
  id: string;
  /** Email address */
  email: string;
  /** Phone number */
  phone: string;
  /** First name */
  name: string;
  /** Last name */
  surname: string;
  /** Account status */
  status: Status;
  /** User role/type */
  type: UserType;
}

export const USER_PACKAGE_NAME = 'user';

/**
 * UserProxyService manages user data and operations
 * Provides CRUD operations, search, and permissions management
 */

export interface UserProxyServiceClient {
  /** Create a new user */

  addUser(request: AddUserRequest, metadata?: Metadata): Observable<UserResponse>;

  /** Retrieve user by ID */

  getUser(request: GetUserRequest, metadata?: Metadata): Observable<UserResponse>;

  /** Search user by email */

  getUserByEmail(request: GetUserByEmailRequest, metadata?: Metadata): Observable<UserResponse>;

  /** Search user by phone number */

  getUserByPhone(request: GetUserByPhoneRequest, metadata?: Metadata): Observable<UserResponse>;

  /** Update user information (all optional fields) */

  updateUser(request: UpdateUserRequest, metadata?: Metadata): Observable<UserResponse>;

  /** Update user status (ACTIVE, SUSPENDED, BANNED, etc.) */

  updateUserStatus(request: UpdateUserStatusRequest, metadata?: Metadata): Observable<UserResponse>;

  /** Update user role/type permissions */

  updateUserRole(request: UpdateUserRoleRequest, metadata?: Metadata): Observable<UserResponse>;

  /** Delete user by ID */

  removeUser(request: RemoveUserRequest, metadata?: Metadata): Observable<UserResponse>;

  /** Retrieve all users with pagination */

  getAllUsers(request: GetAllUsersRequest, metadata?: Metadata): Observable<GetAllUsersResponse>;

  /** Check if user exists by email */

  checkExist(request: CheckExistRequest, metadata?: Metadata): Observable<CheckExistResponse>;
}

/**
 * UserProxyService manages user data and operations
 * Provides CRUD operations, search, and permissions management
 */

export interface UserProxyServiceController {
  /** Create a new user */

  addUser(
    request: AddUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  /** Retrieve user by ID */

  getUser(
    request: GetUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  /** Search user by email */

  getUserByEmail(
    request: GetUserByEmailRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  /** Search user by phone number */

  getUserByPhone(
    request: GetUserByPhoneRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  /** Update user information (all optional fields) */

  updateUser(
    request: UpdateUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  /** Update user status (ACTIVE, SUSPENDED, BANNED, etc.) */

  updateUserStatus(
    request: UpdateUserStatusRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  /** Update user role/type permissions */

  updateUserRole(
    request: UpdateUserRoleRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  /** Delete user by ID */

  removeUser(
    request: RemoveUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  /** Retrieve all users with pagination */

  getAllUsers(
    request: GetAllUsersRequest,
    metadata?: Metadata,
  ): Promise<GetAllUsersResponse> | Observable<GetAllUsersResponse> | GetAllUsersResponse;

  /** Check if user exists by email */

  checkExist(
    request: CheckExistRequest,
    metadata?: Metadata,
  ): Promise<CheckExistResponse> | Observable<CheckExistResponse> | CheckExistResponse;
}

export function UserProxyServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'addUser',
      'getUser',
      'getUserByEmail',
      'getUserByPhone',
      'updateUser',
      'updateUserStatus',
      'updateUserRole',
      'removeUser',
      'getAllUsers',
      'checkExist',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('UserProxyService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('UserProxyService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_PROXY_SERVICE_NAME = 'UserProxyService';
